globalThis.HOMEWORK_QUESTION_SCRIPT_PATHS = [
  "questions/hebrew/hebrew-expanded-words.js",
  "questions/hebrew/hebrew-words.js",
  "questions/hebrew/hebrew-image-words.js",
  "questions/science/science.js",
  "questions/science/science-evidence.js",
  "questions/general-knowledge.js",
  "questions/math/math-skill-studios.js",
  "questions/math/algebra.js",
  "questions/math/negative-numbers.js",
  "questions/math/percentages.js",
  "questions/math/applied-word-problems.js",
  "questions/math/visual-math.js",
  "questions/math/visual-measurement.js",
  "questions/reasoning/logic.js",
  "questions/reasoning/rationality.js",
  "questions/geography/geography-map.js",
  "questions/geography/geography.js",
  "questions/geography/population.js",
  "questions/history/history.js",
  "questions/computing/computing.js",
  "questions/life-skills/financial-literacy.js",
  "questions/math/measurement.js",
  "questions/math/charts-and-graphs.js",
  "questions/math/calendar.js",
  "questions/math/estimation.js",
  "questions/math/probability.js",
  "questions/geography/maps-and-directions.js",
  "questions/life-skills/health-and-first-aid.js",
  "questions/life-skills/nutrition.js",
  "questions/life-skills/household-problem-solving.js",
  "questions/math/fraction-visual-interactives.js",
  "questions/math/fractions.js",
  "questions/math/fractions-and-ratios.js",
  "questions/english/reading-comprehension.js",
  "questions/reasoning/spatial-reasoning.js",
  "questions/reasoning/logic-spatial-puzzles.js",
  "questions/category-drag.js",
  "questions/english/sentence-drag-english.js",
  "questions/hebrew/sentence-drag-hebrew.js",
  "questions/hebrew/hebrew.js",
  "questions/english/vocabulary-grammar.js",
  "questions/hebrew/adult-hebrew-module.js",
];

globalThis.HOMEWORK_LAZY_QUESTION_SCRIPT_PATHS = {
  "geography-map": "questions/geography/geography-map-data.js",
};
