const {
  OPTION_LABELS,
  SESSION_HISTORY_STORAGE_KEY,
  SESSION_HISTORY_CSV_MIME_TYPE,
  SELECTED_USER_STORAGE_KEY,
  MAX_SAVED_SESSIONS,
  QUESTION_COUNT_OPTIONS,
  SPEED_ROUND_QUESTION_COUNT,
  SPEED_ROUND_SECONDS,
  SPEED_ROUND_MS,
  ADULT_USER_ID,
  ADULT_SESSION_DEFAULT_QUESTION_COUNT,
  ADULT_MATH_INTERVAL,
  ADULT_GEOGRAPHY_SHARE,
  MAX_SESSION_DIFFICULTY,
  FIXED_ADULT_SESSION_DIFFICULTY,
  DEFAULT_HEBREW_WRITING_TAIL_COUNT,
  HEBREW_ONLY_WRITING_TAIL_COUNT,
  RESERVED_MAP_CATEGORY,
  LANGUAGE_DRAG_INTERVAL,
  HEBREW_FINAL_LETTER_INTERVAL,
  HEBREW_IMAGE_DRAG_SHARE,
  HEBREW_MATCHING_PAIR_COUNT,
  HEBREW_OPPOSITES_PAIR_COUNT,
  GENERATED_CATEGORY_DRAG_SHARES,
  HEBREW_OPPOSITE_PAIR_DEFINITIONS,
  REVIEW_FOCUS_SHARE,
  REVIEW_RECENCY_DECAY,
  SNAPSHOT_DATE_PATTERN,
  CORE_SESSION_CATEGORIES,
  NON_CORE_SESSION_CATEGORIES,
  REVIEW_FOCUS_ALLOWED_CATEGORIES,
  SESSION_CATEGORY_ORDER,
  CORE_CATEGORY_SHARE,
  createUniformCategoryDifficulties,
  USER_PROFILES,
  CATEGORY_LABELS,
  USER_PROFILE_MAP,
  DIFFICULTY_LEVEL_STYLES,
  NON_HEBREW_DIFFICULTY_WEIGHTS,
  EXTENDED_MATH_CATEGORIES,
  SESSION_PRESETS,
} = window.HomeworkApp.config;

const CHART_BAR_TEMPLATES = [
  {
    title: "Favorite Fruits",
    xAxisLabel: "Votes",
    yAxisLabel: "Fruit",
    labels: ["Apples", "Bananas", "Grapes", "Oranges"],
    prompts: {
      most: () => "Which fruit got the most votes?",
      secondMost: () => "Which fruit got the second most votes?",
      fewest: () => "Which fruit got the fewest votes?",
      exact: (label) => `How many votes did ${label.toLowerCase()} get?`,
      total: () => "How many votes were there altogether?",
      difference: (larger, smaller) =>
        `How many more votes did ${larger.toLowerCase()} get than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label} got ${formatUnitCount(item.value, "vote")}`,
  },
  {
    title: "Pet Votes",
    xAxisLabel: "Votes",
    yAxisLabel: "Pet",
    labels: ["Dogs", "Cats", "Fish", "Birds"],
    prompts: {
      most: () => "Which pet got the most votes?",
      secondMost: () => "Which pet got the second most votes?",
      fewest: () => "Which pet got the fewest votes?",
      exact: (label) => `How many votes did ${label.toLowerCase()} get?`,
      total: () => "How many votes were there altogether?",
      difference: (larger, smaller) =>
        `How many more votes did ${larger.toLowerCase()} get than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label} got ${formatUnitCount(item.value, "vote")}`,
  },
  {
    title: "Toy Boxes",
    xAxisLabel: "Pieces",
    yAxisLabel: "Toy type",
    labels: ["Blocks", "Cars", "Balls", "Dolls"],
    prompts: {
      most: () => "Which toy type has the most pieces?",
      secondMost: () => "Which toy type has the second most pieces?",
      fewest: () => "Which toy type has the fewest pieces?",
      exact: (label) => `How many ${label.toLowerCase()} are there?`,
      total: () => "How many toy pieces are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "piece")}`,
  },
  {
    title: "Snack Sales",
    xAxisLabel: "Snacks sold",
    yAxisLabel: "Snack",
    labels: ["Crackers", "Yogurt", "Cheese", "Apples"],
    prompts: {
      most: () => "Which snack sold the most?",
      secondMost: () => "Which snack sold the second most?",
      fewest: () => "Which snack sold the fewest?",
      exact: (label) => `How many ${label.toLowerCase()} were sold?`,
      total: () => "How many snacks were sold altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} were sold than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "snack")} sold`,
  },
  {
    title: "Books Read",
    xAxisLabel: "Books read",
    yAxisLabel: "Student",
    labels: ["Noga", "Gideon", "Gabriel", "Eden"],
    prompts: {
      most: () => "Who read the most books?",
      secondMost: () => "Who read the second most books?",
      fewest: () => "Who read the fewest books?",
      exact: (label) => `How many books did ${label} read?`,
      total: () => "How many books were read altogether?",
      difference: (larger, smaller) => `How many more books did ${larger} read than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label} read ${formatUnitCount(item.value, "book")}`,
  },
  {
    title: "Sticker Colors",
    xAxisLabel: "Stickers",
    yAxisLabel: "Color",
    labels: ["Red", "Blue", "Green", "Yellow"],
    prompts: {
      most: () => "Which color has the most stickers?",
      secondMost: () => "Which color has the second most stickers?",
      fewest: () => "Which color has the fewest stickers?",
      exact: (label) => `How many ${label.toLowerCase()} stickers are there?`,
      total: () => "How many stickers are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} stickers are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "sticker")}`,
  },
  {
    title: "Favorite Ice Creams",
    xAxisLabel: "Votes",
    yAxisLabel: "Ice cream",
    labels: ["Vanilla", "Chocolate", "Strawberry", "Mint"],
    prompts: {
      most: () => "Which ice cream got the most votes?",
      secondMost: () => "Which ice cream got the second most votes?",
      fewest: () => "Which ice cream got the fewest votes?",
      exact: (label) => `How many votes did ${label.toLowerCase()} get?`,
      total: () => "How many votes were there altogether?",
      difference: (larger, smaller) =>
        `How many more votes did ${larger.toLowerCase()} get than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label} got ${formatUnitCount(item.value, "vote")}`,
  },
  {
    title: "Recess Games",
    xAxisLabel: "Votes",
    yAxisLabel: "Game",
    labels: ["Tag", "Soccer", "Hopscotch", "Four Square"],
    prompts: {
      most: () => "Which recess game got the most votes?",
      secondMost: () => "Which recess game got the second most votes?",
      fewest: () => "Which recess game got the fewest votes?",
      exact: (label) => `How many votes did ${label.toLowerCase()} get?`,
      total: () => "How many votes were there altogether?",
      difference: (larger, smaller) =>
        `How many more votes did ${larger.toLowerCase()} get than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label} got ${formatUnitCount(item.value, "vote")}`,
  },
  {
    title: "Backpack Items",
    xAxisLabel: "Items",
    yAxisLabel: "Backpack item",
    labels: ["Pencils", "Crayons", "Markers", "Erasers"],
    prompts: {
      most: () => "Which backpack item appears the most?",
      secondMost: () => "Which backpack item appears the second most?",
      fewest: () => "Which backpack item appears the fewest times?",
      exact: (label) => `How many ${label.toLowerCase()} are in the backpack?`,
      total: () => "How many backpack items are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "item")}`,
  },
  {
    title: "Garden Flowers",
    xAxisLabel: "Flowers",
    yAxisLabel: "Flower",
    labels: ["Roses", "Tulips", "Daisies", "Sunflowers"],
    prompts: {
      most: () => "Which flower has the most blooms?",
      secondMost: () => "Which flower has the second most blooms?",
      fewest: () => "Which flower has the fewest blooms?",
      exact: (label) => `How many ${label.toLowerCase()} are in the garden?`,
      total: () => "How many flowers are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} are in the garden than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "flower")}`,
  },
  {
    title: "Lunch Orders",
    xAxisLabel: "Orders",
    yAxisLabel: "Lunch",
    labels: ["Pizza", "Pasta", "Salad", "Soup"],
    prompts: {
      most: () => "Which lunch got the most orders?",
      secondMost: () => "Which lunch got the second most orders?",
      fewest: () => "Which lunch got the fewest orders?",
      exact: (label) => `How many ${label.toLowerCase()} lunches were ordered?`,
      total: () => "How many lunches were ordered altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} lunches were ordered than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "order")}`,
  },
  {
    title: "Craft Beads",
    xAxisLabel: "Beads",
    yAxisLabel: "Bead color",
    labels: ["Red", "Blue", "Green", "Gold"],
    prompts: {
      most: () => "Which bead color appears the most?",
      secondMost: () => "Which bead color appears the second most?",
      fewest: () => "Which bead color appears the fewest times?",
      exact: (label) => `How many ${label.toLowerCase()} beads are there?`,
      total: () => "How many beads are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} beads are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "bead")}`,
  },
  {
    title: "Playground Climbs",
    xAxisLabel: "Climbs",
    yAxisLabel: "Student",
    labels: ["Ava", "Leo", "Mia", "Noah"],
    prompts: {
      most: () => "Who climbed the ladder the most times?",
      secondMost: () => "Who climbed the ladder the second most times?",
      fewest: () => "Who climbed the ladder the fewest times?",
      exact: (label) => `How many times did ${label} climb the ladder?`,
      total: () => "How many climbs were there altogether?",
      difference: (larger, smaller) => `How many more climbs did ${larger} have than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "climb")}`,
  },
  {
    title: "Treasure Chest",
    xAxisLabel: "Treasures",
    yAxisLabel: "Treasure type",
    labels: ["Coins", "Gems", "Keys", "Maps"],
    prompts: {
      most: () => "Which treasure appears the most?",
      secondMost: () => "Which treasure appears the second most?",
      fewest: () => "Which treasure appears the fewest times?",
      exact: (label) => `How many ${label.toLowerCase()} are in the treasure chest?`,
      total: () => "How many treasures are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "treasure")}`,
  },
  {
    title: "Favorite Instruments",
    xAxisLabel: "Votes",
    yAxisLabel: "Instrument",
    labels: ["Drums", "Piano", "Guitar", "Flute"],
    prompts: {
      most: () => "Which instrument got the most votes?",
      secondMost: () => "Which instrument got the second most votes?",
      fewest: () => "Which instrument got the fewest votes?",
      exact: (label) => `How many votes did ${label.toLowerCase()} get?`,
      total: () => "How many votes were there altogether?",
      difference: (larger, smaller) =>
        `How many more votes did ${larger.toLowerCase()} get than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label} got ${formatUnitCount(item.value, "vote")}`,
  },
  {
    title: "Farm Animals",
    xAxisLabel: "Animals",
    yAxisLabel: "Animal",
    labels: ["Cows", "Pigs", "Sheep", "Goats"],
    prompts: {
      most: () => "Which farm animal is shown the most?",
      secondMost: () => "Which farm animal is shown the second most?",
      fewest: () => "Which farm animal is shown the fewest times?",
      exact: (label) => `How many ${label.toLowerCase()} are there?`,
      total: () => "How many farm animals are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "animal")}`,
  },
  {
    title: "Reading Corner Books",
    xAxisLabel: "Books",
    yAxisLabel: "Book bin",
    labels: ["Space", "Animals", "Mystery", "Sports"],
    prompts: {
      most: () => "Which book bin has the most books?",
      secondMost: () => "Which book bin has the second most books?",
      fewest: () => "Which book bin has the fewest books?",
      exact: (label) => `How many ${label.toLowerCase()} books are in the bin?`,
      total: () => "How many books are there altogether?",
      difference: (larger, smaller) =>
        `How many more ${larger.toLowerCase()} books are there than ${smaller.toLowerCase()} books?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "book")}`,
  },
  {
    title: "Block Towers",
    xAxisLabel: "Blocks",
    yAxisLabel: "Tower",
    labels: ["Tower A", "Tower B", "Tower C", "Tower D"],
    prompts: {
      most: () => "Which tower is tallest?",
      secondMost: () => "Which tower is the second tallest?",
      fewest: () => "Which tower is shortest?",
      exact: (label) => `How many blocks tall is ${label}?`,
      total: () => "How many blocks are there altogether?",
      difference: (larger, smaller) => `How many more blocks tall is ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "block")} tall`,
  },
];
const CHART_TABLE_TEMPLATES = [
  {
    title: "Library Visits",
    leftLabel: "Day",
    rightLabel: "Visitors",
    labels: ["Mon", "Tue", "Wed", "Thu"],
    prompts: {
      most: () => "Which day had the most visitors?",
      secondMost: () => "Which day had the second most visitors?",
      fewest: () => "Which day had the fewest visitors?",
      exact: (label) => `How many visitors were there on ${label}?`,
      total: () => "How many visitors were there altogether?",
      combined: (left, right) => `How many visitors were there on ${left} and ${right} altogether?`,
      difference: (larger, smaller) =>
        `How many more visitors were there on ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "visitor")}`,
  },
  {
    title: "Water Cups",
    leftLabel: "Day",
    rightLabel: "Cups",
    labels: ["Sun", "Mon", "Tue", "Wed"],
    prompts: {
      most: () => "Which day had the most cups of water?",
      secondMost: () => "Which day had the second most cups of water?",
      fewest: () => "Which day had the fewest cups of water?",
      exact: (label) => `How many cups of water were drunk on ${label}?`,
      total: () => "How many cups of water were drunk altogether?",
      combined: (left, right) =>
        `How many cups of water were drunk on ${left} and ${right} altogether?`,
      difference: (larger, smaller) =>
        `How many more cups of water were drunk on ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "cup")} of water`,
  },
  {
    title: "Tree Heights",
    leftLabel: "Tree",
    rightLabel: "Meters",
    labels: ["Oak", "Pine", "Palm", "Maple"],
    prompts: {
      most: () => "Which tree is tallest?",
      secondMost: () => "Which tree is the second tallest?",
      fewest: () => "Which tree is shortest?",
      exact: (label) => `How tall is ${label} in meters?`,
      total: () => "What is the total height of all the trees in meters?",
      combined: (left, right) => `What is the total height of ${left} and ${right} in meters?`,
      difference: (larger, smaller) => `How many meters taller is ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "meter")}`,
  },
  {
    title: "Team Points",
    leftLabel: "Team",
    rightLabel: "Points",
    labels: ["Red", "Blue", "Green", "Yellow"],
    prompts: {
      most: () => "Which team scored the most points?",
      secondMost: () => "Which team scored the second most points?",
      fewest: () => "Which team scored the fewest points?",
      exact: (label) => `How many points did the ${label} team score?`,
      total: () => "How many points were scored altogether?",
      combined: (left, right) =>
        `How many points did the ${left} and ${right} teams score altogether?`,
      difference: (larger, smaller) =>
        `How many more points did the ${larger} team score than the ${smaller} team?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "point")}`,
  },
  {
    title: "Class Jobs",
    leftLabel: "Job",
    rightLabel: "Students",
    labels: ["Clean", "Read", "Draw", "Build"],
    prompts: {
      most: () => "Which job had the most students?",
      secondMost: () => "Which job had the second most students?",
      fewest: () => "Which job had the fewest students?",
      exact: (label) => `How many students had the ${label.toLowerCase()} job?`,
      total: () => "How many students are shown altogether?",
      combined: (left, right) =>
        `How many students had the ${left.toLowerCase()} and ${right.toLowerCase()} jobs altogether?`,
      difference: (larger, smaller) =>
        `How many more students had the ${larger.toLowerCase()} job than the ${smaller.toLowerCase()} job?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "student")}`,
  },
  {
    title: "Plant Heights",
    leftLabel: "Plant",
    rightLabel: "Cm",
    labels: ["A", "B", "C", "D"],
    prompts: {
      most: () => "Which plant is tallest?",
      secondMost: () => "Which plant is the second tallest?",
      fewest: () => "Which plant is shortest?",
      exact: (label) => `How tall is plant ${label} in centimeters?`,
      total: () => "What is the total height of all the plants in centimeters?",
      combined: (left, right) =>
        `What is the total height of plants ${left} and ${right} in centimeters?`,
      difference: (larger, smaller) =>
        `How many centimeters taller is plant ${larger} than plant ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "centimeter")}`,
  },
  {
    title: "Backyard Birds",
    leftLabel: "Bird",
    rightLabel: "Sightings",
    labels: ["Robin", "Crow", "Sparrow", "Bluejay"],
    prompts: {
      most: () => "Which bird had the most sightings?",
      secondMost: () => "Which bird had the second most sightings?",
      fewest: () => "Which bird had the fewest sightings?",
      exact: (label) => `How many times was a ${label.toLowerCase()} seen?`,
      total: () => "How many bird sightings were there altogether?",
      combined: (left, right) =>
        `How many bird sightings were there for ${left.toLowerCase()} and ${right.toLowerCase()} altogether?`,
      difference: (larger, smaller) =>
        `How many more sightings were there for ${larger.toLowerCase()} than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "sighting")}`,
  },
  {
    title: "Homework Pages",
    leftLabel: "Subject",
    rightLabel: "Pages",
    labels: ["Math", "Reading", "Science", "Writing"],
    prompts: {
      most: () => "Which subject had the most pages?",
      secondMost: () => "Which subject had the second most pages?",
      fewest: () => "Which subject had the fewest pages?",
      exact: (label) => `How many pages were finished in ${label.toLowerCase()}?`,
      total: () => "How many homework pages were finished altogether?",
      combined: (left, right) =>
        `How many homework pages were finished in ${left.toLowerCase()} and ${right.toLowerCase()} altogether?`,
      difference: (larger, smaller) =>
        `How many more pages were finished in ${larger.toLowerCase()} than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "page")}`,
  },
  {
    title: "Bus Stop Riders",
    leftLabel: "Stop",
    rightLabel: "Riders",
    labels: ["Oak", "Pine", "Maple", "Lake"],
    prompts: {
      most: () => "Which stop had the most riders?",
      secondMost: () => "Which stop had the second most riders?",
      fewest: () => "Which stop had the fewest riders?",
      exact: (label) => `How many riders got on at ${label} stop?`,
      total: () => "How many riders were there altogether?",
      combined: (left, right) =>
        `How many riders got on at ${left} and ${right} stops altogether?`,
      difference: (larger, smaller) =>
        `How many more riders got on at ${larger} stop than ${smaller} stop?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "rider")}`,
  },
  {
    title: "Chore Minutes",
    leftLabel: "Chore",
    rightLabel: "Minutes",
    labels: ["Sweep", "Dust", "Wash", "Fold"],
    prompts: {
      most: () => "Which chore took the most minutes?",
      secondMost: () => "Which chore took the second most minutes?",
      fewest: () => "Which chore took the fewest minutes?",
      exact: (label) => `How many minutes were spent on ${label.toLowerCase()}?`,
      total: () => "How many chore minutes are shown altogether?",
      combined: (left, right) =>
        `How many minutes were spent on ${left.toLowerCase()} and ${right.toLowerCase()} altogether?`,
      difference: (larger, smaller) =>
        `How many more minutes were spent on ${larger.toLowerCase()} than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "minute")}`,
  },
  {
    title: "Cupcake Trays",
    leftLabel: "Tray",
    rightLabel: "Cupcakes",
    labels: ["A", "B", "C", "D"],
    prompts: {
      most: () => "Which tray has the most cupcakes?",
      secondMost: () => "Which tray has the second most cupcakes?",
      fewest: () => "Which tray has the fewest cupcakes?",
      exact: (label) => `How many cupcakes are on tray ${label}?`,
      total: () => "How many cupcakes are there altogether?",
      combined: (left, right) => `How many cupcakes are on trays ${left} and ${right} altogether?`,
      difference: (larger, smaller) =>
        `How many more cupcakes are on tray ${larger} than tray ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "cupcake")}`,
  },
  {
    title: "Can Collection",
    leftLabel: "Team",
    rightLabel: "Cans",
    labels: ["Red", "Blue", "Green", "Gold"],
    prompts: {
      most: () => "Which team collected the most cans?",
      secondMost: () => "Which team collected the second most cans?",
      fewest: () => "Which team collected the fewest cans?",
      exact: (label) => `How many cans did the ${label.toLowerCase()} team collect?`,
      total: () => "How many cans were collected altogether?",
      combined: (left, right) =>
        `How many cans did the ${left.toLowerCase()} and ${right.toLowerCase()} teams collect altogether?`,
      difference: (larger, smaller) =>
        `How many more cans did the ${larger.toLowerCase()} team collect than the ${smaller.toLowerCase()} team?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "can")}`,
  },
  {
    title: "Jump Rope Counts",
    leftLabel: "Student",
    rightLabel: "Jumps",
    labels: ["Lia", "Omar", "Ruth", "Ben"],
    prompts: {
      most: () => "Which student had the most jumps?",
      secondMost: () => "Which student had the second most jumps?",
      fewest: () => "Which student had the fewest jumps?",
      exact: (label) => `How many jumps did ${label} do?`,
      total: () => "How many jumps were there altogether?",
      combined: (left, right) => `How many jumps did ${left} and ${right} do altogether?`,
      difference: (larger, smaller) =>
        `How many more jumps did ${larger} do than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "jump")}`,
  },
  {
    title: "Pencil Lengths",
    leftLabel: "Pencil",
    rightLabel: "Cm",
    labels: ["Red", "Blue", "Green", "Yellow"],
    prompts: {
      most: () => "Which pencil is longest?",
      secondMost: () => "Which pencil is the second longest?",
      fewest: () => "Which pencil is shortest?",
      exact: (label) => `How long is the ${label.toLowerCase()} pencil in centimeters?`,
      total: () => "What is the total length of all the pencils in centimeters?",
      combined: (left, right) =>
        `What is the total length of the ${left.toLowerCase()} and ${right.toLowerCase()} pencils in centimeters?`,
      difference: (larger, smaller) =>
        `How many centimeters longer is the ${larger.toLowerCase()} pencil than the ${smaller.toLowerCase()} pencil?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "centimeter")}`,
  },
  {
    title: "Zoo Gate Counts",
    leftLabel: "Gate",
    rightLabel: "Visitors",
    labels: ["North", "South", "East", "West"],
    prompts: {
      most: () => "Which gate had the most visitors?",
      secondMost: () => "Which gate had the second most visitors?",
      fewest: () => "Which gate had the fewest visitors?",
      exact: (label) => `How many visitors came through the ${label.toLowerCase()} gate?`,
      total: () => "How many visitors came through all the gates altogether?",
      combined: (left, right) =>
        `How many visitors came through the ${left.toLowerCase()} and ${right.toLowerCase()} gates altogether?`,
      difference: (larger, smaller) =>
        `How many more visitors came through the ${larger.toLowerCase()} gate than the ${smaller.toLowerCase()} gate?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "visitor")}`,
  },
  {
    title: "Soccer Practice Goals",
    leftLabel: "Player",
    rightLabel: "Goals",
    labels: ["Ava", "Leo", "Mia", "Noah"],
    prompts: {
      most: () => "Which player scored the most goals?",
      secondMost: () => "Which player scored the second most goals?",
      fewest: () => "Which player scored the fewest goals?",
      exact: (label) => `How many goals did ${label} score?`,
      total: () => "How many goals were scored altogether?",
      combined: (left, right) => `How many goals did ${left} and ${right} score altogether?`,
      difference: (larger, smaller) =>
        `How many more goals did ${larger} score than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "goal")}`,
  },
  {
    title: "Snack Table",
    leftLabel: "Snack",
    rightLabel: "Pieces",
    labels: ["Pretzels", "Carrots", "Crackers", "Cheese"],
    prompts: {
      most: () => "Which snack has the most pieces?",
      secondMost: () => "Which snack has the second most pieces?",
      fewest: () => "Which snack has the fewest pieces?",
      exact: (label) => `How many pieces of ${label.toLowerCase()} are there?`,
      total: () => "How many snack pieces are there altogether?",
      combined: (left, right) =>
        `How many pieces of ${left.toLowerCase()} and ${right.toLowerCase()} are there altogether?`,
      difference: (larger, smaller) =>
        `How many more pieces of ${larger.toLowerCase()} are there than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "piece")}`,
  },
  {
    title: "Toy Car Distances",
    leftLabel: "Car",
    rightLabel: "Meters",
    labels: ["Red", "Blue", "Green", "Yellow"],
    prompts: {
      most: () => "Which toy car rolled the farthest?",
      secondMost: () => "Which toy car rolled the second farthest?",
      fewest: () => "Which toy car rolled the shortest distance?",
      exact: (label) => `How far did the ${label.toLowerCase()} car roll in meters?`,
      total: () => "What is the total distance rolled by all the toy cars in meters?",
      combined: (left, right) =>
        `What is the total distance rolled by the ${left.toLowerCase()} and ${right.toLowerCase()} cars in meters?`,
      difference: (larger, smaller) =>
        `How many meters farther did the ${larger.toLowerCase()} car roll than the ${smaller.toLowerCase()} car?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "meter")}`,
  },
  {
    title: "Reading Minutes",
    leftLabel: "Day",
    rightLabel: "Minutes",
    labels: ["Mon", "Tue", "Wed", "Thu"],
    prompts: {
      most: () => "Which day had the most reading minutes?",
      secondMost: () => "Which day had the second most reading minutes?",
      fewest: () => "Which day had the fewest reading minutes?",
      exact: (label) => `How many minutes were spent reading on ${label}?`,
      total: () => "How many reading minutes were there altogether?",
      combined: (left, right) =>
        `How many reading minutes were there on ${left} and ${right} altogether?`,
      difference: (larger, smaller) =>
        `How many more reading minutes were there on ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "minute")} reading`,
  },
  {
    title: "Weather Over Days",
    leftLabel: "Day",
    rightLabel: "Degrees",
    labels: ["Mon", "Tue", "Wed", "Thu"],
    prompts: {
      most: () => "Which day was warmest?",
      secondMost: () => "Which day was second warmest?",
      fewest: () => "Which day was coolest?",
      exact: (label) => `What was the temperature on ${label}?`,
      total: () => "What is the total of the four temperatures?",
      combined: (left, right) => `What is the total temperature for ${left} and ${right}?`,
      difference: (larger, smaller) =>
        `How many degrees warmer was ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "degree")}`,
  },
  {
    title: "Savings Tracker",
    leftLabel: "Week",
    rightLabel: "Shekels",
    labels: ["Week 1", "Week 2", "Week 3", "Week 4"],
    prompts: {
      most: () => "Which week had the most savings?",
      secondMost: () => "Which week had the second most savings?",
      fewest: () => "Which week had the fewest savings?",
      exact: (label) => `How many shekels were saved in ${label}?`,
      total: () => "How many shekels were saved altogether?",
      combined: (left, right) => `How many shekels were saved in ${left} and ${right} altogether?`,
      difference: (larger, smaller) =>
        `How many more shekels were saved in ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "shekel")}`,
  },
  {
    title: "Screen Time",
    leftLabel: "Day",
    rightLabel: "Minutes",
    labels: ["Mon", "Tue", "Wed", "Thu"],
    prompts: {
      most: () => "Which day had the most screen time?",
      secondMost: () => "Which day had the second most screen time?",
      fewest: () => "Which day had the least screen time?",
      exact: (label) => `How many minutes of screen time were there on ${label}?`,
      total: () => "How many screen-time minutes were there altogether?",
      combined: (left, right) =>
        `How many screen-time minutes were there on ${left} and ${right} altogether?`,
      difference: (larger, smaller) =>
        `How many more screen-time minutes were there on ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "minute")} screen time`,
  },
  {
    title: "Science Experiment Trials",
    leftLabel: "Trial",
    rightLabel: "Cm",
    labels: ["Trial 1", "Trial 2", "Trial 3", "Trial 4"],
    prompts: {
      most: () => "Which trial had the longest distance?",
      secondMost: () => "Which trial had the second longest distance?",
      fewest: () => "Which trial had the shortest distance?",
      exact: (label) => `How many centimeters did the object move in ${label}?`,
      total: () => "What is the total distance across all trials?",
      combined: (left, right) => `What is the total distance for ${left} and ${right}?`,
      difference: (larger, smaller) =>
        `How many centimeters farther was ${larger} than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "centimeter")}`,
  },
  {
    title: "School Votes",
    leftLabel: "Choice",
    rightLabel: "Votes",
    labels: ["Art Day", "Sports Day", "Movie", "Science Fair"],
    prompts: {
      most: () => "Which choice got the most votes?",
      secondMost: () => "Which choice got the second most votes?",
      fewest: () => "Which choice got the fewest votes?",
      exact: (label) => `How many votes did ${label} get?`,
      total: () => "How many votes were there altogether?",
      combined: (left, right) => `How many votes did ${left} and ${right} get altogether?`,
      difference: (larger, smaller) =>
        `How many more votes did ${larger} get than ${smaller}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "vote")}`,
  },
  {
    title: "Bus Schedule Waits",
    leftLabel: "Bus",
    rightLabel: "Minutes late",
    labels: ["7:30", "7:45", "8:00", "8:15"],
    prompts: {
      most: () => "Which bus was latest?",
      secondMost: () => "Which bus was second latest?",
      fewest: () => "Which bus was closest to on time?",
      exact: (label) => `How many minutes late was the ${label} bus?`,
      total: () => "How many late minutes were there altogether?",
      combined: (left, right) =>
        `How many late minutes were there for the ${left} and ${right} buses altogether?`,
      difference: (larger, smaller) =>
        `How many more minutes late was the ${larger} bus than the ${smaller} bus?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "minute")} late`,
  },
  {
    title: "Sports Practice",
    leftLabel: "Activity",
    rightLabel: "Minutes",
    labels: ["Running", "Passing", "Shooting", "Stretching"],
    prompts: {
      most: () => "Which activity took the most practice time?",
      secondMost: () => "Which activity took the second most practice time?",
      fewest: () => "Which activity took the least practice time?",
      exact: (label) => `How many minutes were spent on ${label.toLowerCase()}?`,
      total: () => "How many sports-practice minutes were there altogether?",
      combined: (left, right) =>
        `How many minutes were spent on ${left.toLowerCase()} and ${right.toLowerCase()} altogether?`,
      difference: (larger, smaller) =>
        `How many more minutes were spent on ${larger.toLowerCase()} than ${smaller.toLowerCase()}?`,
    },
    summaryItem: (item) => `${item.label}: ${formatUnitCount(item.value, "minute")}`,
  },
];

const HEBREW_NIKKUD_OVERRIDES = {
  "ב-": "בְּ-",
  "כ-": "כְּ-",
  "ל-": "לְ-",
  "מ-": "מִ-",
  "ו-": "וְ-",
  "ה-": "הַ-",
  "אבא": "אַבָּא",
  "אבטיח": "אֲבַטִּיחַ",
  "אגס": "אַגָּס",
  "אדום": "אָדוֹם",
  "אוזן": "אֹזֶן",
  "אוטובוס": "אוֹטוֹבּוּס",
  "אוכל": "אוֹכֶל",
  "אופניים": "אוֹפַנַּיִם",
  "אורז": "אוֹרֶז",
  "אחות": "אָחוֹת",
  "אח": "אָח",
  "איך": "אֵיךְ",
  "אימא": "אִמָּא",
  "אישה": "אִשָּׁה",
  "איש": "אִישׁ",
  "אמא": "אִמָּא",
  "אנחנו": "אֲנַחְנוּ",
  "אני": "אֲנִי",
  "אננס": "אָנָנָס",
  "אפרסק": "אֲפַרְסֵק",
  "אורי": "אוּרִי",
  "אבל": "אֲבָל",
  "את": "אַתְ",
  "אתה": "אַתָּה",
  "אתם": "אַתֶּם",
  "אתן": "אַתֶּן",
  "איפה": "אֵיפֹה",
  "ארוחת בוקר": "אֲרוּחַת בֹּקֶר",
  "ארוחת ערב": "אֲרוּחַת עֶרֶב",
  "בית": "בַּיִת",
  "בית ספר": "בֵּית סֵפֶר",
  "בגדים": "בְּגָדִים",
  "ביצה": "בֵּיצָה",
  "בוקר": "בֹּקֶר",
  "ביחד": "בְּיַחַד",
  "בפנים": "בִּפְנִים",
  "בבקשה": "בְּבַקָּשָׁה",
  "בן": "בֵּן",
  "בננה": "בָּנָנָה",
  "בת": "בַּת",
  "גבינה": "גְּבִינָה",
  "גבריאל": "גַּבְרִיאֵל",
  "גדול": "גָּדוֹל",
  "גדעון": "גִּדְעוֹן",
  "גזר": "גֶּזֶר",
  "גלידה": "גְּלִידָה",
  "דנה": "דָּנָה",
  "דג": "דָּג",
  "דבש": "דְּבַשׁ",
  "דובדבן": "דֻּבְדְּבָן",
  "דני": "דָּנִי",
  "דרך": "דֶּרֶךְ",
  "דלת": "דֶּלֶת",
  "דף": "דַּף",
  "הבא": "הַבָּא",
  "הוא": "הוּא",
  "היא": "הִיא",
  "הם": "הֵם",
  "הן": "הֵן",
  "היום": "הַיּוֹם",
  "הרים": "הָרִים",
  "וילון": "וִילוֹן",
  "זמן": "זְמַן",
  "חבר": "חָבֵר",
  "חדר אמבטיה": "חֲדַר אַמְבַּטְיָה",
  "חדש": "חָדָשׁ",
  "חיות": "חַיּוֹת",
  "חלקי גוף": "חֶלְקֵי גּוּף",
  "חולצה": "חֻלְצָה",
  "חתול": "חָתוּל",
  "חולה": "חוֹלֶה",
  "חזק": "חָזָק",
  "חלב": "חָלָב",
  "חלב אם": "חֲלֵב אֵם",
  "חלש": "חַלָשׁ",
  "ילד": "יֶלֶד",
  "ילדה": "יַלְדָּה",
  "יפה": "יָפֶה",
  "ים": "יָם",
  "ירח": "יָרֵחַ",
  "ירוק": "יָרוֹק",
  "ישן": "יָשָׁן",
  "יש": "יֵשׁ",
  "ישראל": "יִשְׂרָאֵל",
  "יתוש": "יַתּוּשׁ",
  "כדור": "כַּדּוּר",
  "כובע": "כּוֹבַע",
  "כוכב": "כּוֹכָב",
  "כוס": "כּוֹס",
  "כולם": "כּוּלָּם",
  "כלב": "כֶּלֶב",
  "כלום": "כְּלוּם",
  "כחול": "כָּחוֹל",
  "כיסא": "כִּסֵּא",
  "כיתה": "כִּיתָה",
  "כסא": "כִּסֵּא",
  "כסף": "כֶּסֶף",
  "כן": "כֵּן",
  "כמה": "כַּמָּה",
  "כף": "כַּף",
  "כתום": "כָּתוֹם",
  "לאט": "לְאַט",
  "לחם": "לֶחֶם",
  "לבן": "לָבָן",
  "לילה": "לַיְלָה",
  "לימון": "לִימוֹן",
  "למה": "לָמָּה",
  "מה": "מָה",
  "מהיר": "מָהִיר",
  "מהר": "מַהֵר",
  "מים": "מַיִם",
  "מי": "מִי",
  "מלך": "מֶלֶךְ",
  "מלכה": "מַלְכָּה",
  "מזלג": "מַזְלֵג",
  "מחר": "מָחָר",
  "מיטה": "מִטָּה",
  "מכונית": "מְכוֹנִית",
  "מעניין": "מְעַנְיֵן",
  "מפתח": "מַפְתֵּחַ",
  "מראה": "מַרְאָה",
  "מזג אוויר": "מֶזֶג אֲוִיר",
  "מחשב": "מַחְשֵׁב",
  "מדפסת": "מַדְפֶּסֶת",
  "מחברת": "מַחְבֶּרֶת",
  "מטוס": "מַטּוֹס",
  "מטבח": "מִטְבָּח",
  "מתי": "מָתַי",
  "מיה": "מִיָה",
  "מיץ": "מִיץ",
  "מצלמה": "מַצְלֵמָה",
  "מרק": "מָרָק",
  "משפחה": "מִשְׁפָּחָה",
  "נייר": "נְיָר",
  "נמלה": "נְמָלָה",
  "נקי": "נָקִי",
  "נועם": "נוֹעַם",
  "נעליים": "נַעֲלַיִם",
  "ספר": "סֵפֶר",
  "ספרייה": "סִפְרִיָּה",
  "סלון": "סָלוֹן",
  "סליחה": "סְלִיחָה",
  "סיפור": "סִיפּוּר",
  "סבון": "סַבּוֹן",
  "סגול": "סָגוֹל",
  "סגור": "סָגוּר",
  "ספה": "סַפָּה",
  "עגבניה": "עַגְבָנִיָּה",
  "עוגה": "עוּגָה",
  "עוף": "עוֹף",
  "עיר": "עִיר",
  "עט": "עֵט",
  "עין": "עַיִן",
  "עכשיו": "עַכְשָׁיו",
  "עכביש": "עַכָּבִישׁ",
  "עכבר": "עַכְבָּר",
  "עפרון": "עִפָּרוֹן",
  "עץ": "עֵץ",
  "ענבים": "עֲנָבִים",
  "ענן": "עָנָן",
  "פסטה": "פַּסְטָה",
  "צבעים": "צְבָעִים",
  "צעצועים": "צַעֲצוּעִים",
  "פה": "פֹּה",
  "פנים": "פָּנִים",
  "פשוט": "פָּשׁוּט",
  "פרח": "פֶּרַח",
  "פתוח": "פָּתוּחַ",
  "ציפור": "צִפּוֹר",
  "צהוב": "צָהוֹב",
  "קטן": "קָטָן",
  "קפה": "קָפֶה",
  "קערה": "קְעָרָה",
  "קשה": "קָשֶׁה",
  "קצת": "קְצָת",
  "רגל": "רֶגֶל",
  "ראש": "רֹאשׁ",
  "ראשון": "רִאשׁוֹן",
  "רכבת": "רַכֶּבֶת",
  "שעון": "שָׁעוֹן",
  "שיניים": "שִׁנַּיִם",
  "שיעור": "שִׁעוּר",
  "שולחן": "שֻׁלְחָן",
  "שלום": "שָׁלוֹם",
  "שחור": "שָׁחוֹר",
  "שוקולד": "שׁוֹקוֹלָד",
  "שבוע": "שָׁבוּעַ",
  "שעה": "שָׁעָה",
  "שאיבת חלב אם": "שְׁאִיבַת חֲלֵב אֵם",
  "שמש": "שֶׁמֶשׁ",
  "שם": "שָׁם",
  "טלפון": "טֵלֵפוֹן",
  "טלוויזיה": "טֶלֶוִיזְיָה",
  "תודה": "תּוֹדָה",
  "תה": "תֵּה",
  "טבע": "טֶבַע",
  "תחבורה": "תַּחְבּוּרָה",
  "תמונה": "תְּמוּנָה",
  "תינוק": "תִּינוֹק",
  "תיק": "תִּיק",
  "תות": "תּוּת",
  "תפוז": "תַּפּוּז",
  "תפוח": "תַּפּוּחַ",
  "תפוח אדמה": "תַּפּוּחַ אֲדָמָה",
};

// These forms appear in the Hebrew sentence-drag questions but are not covered by
// the transliterated vocabulary bank.
const HEBREW_SENTENCE_NIKKUD_OVERRIDES = {
  "את": "אֶת",
  "אוכלים": "אוֹכְלִים",
  "אוטובוס": "אוֹטוֹבּוּס",
  "אוהב": "אוֹהֵב",
  "אופה": "אוֹפָה",
  "אופים": "אוֹפִים",
  "אורזת": "אוֹרֶזֶת",
  "אותה": "אוֹתָהּ",
  "אותם": "אוֹתָם",
  "אחר": "אַחֵר",
  "אחרי": "אַחֲרֵי",
  "ארוחת": "אֲרוּחַת",
  "בבוקר": "בַּבֹּקֶר",
  "בגינה": "בַּגִּינָה",
  "בודקת": "בּוֹדֶקֶת",
  "בוחרת": "בּוֹחֶרֶת",
  "בונה": "בּוֹנָה",
  "בונים": "בּוֹנִים",
  "בועט": "בּוֹעֵט",
  "בזהירות": "בִּזְהִירוּת",
  "באוטובוס": "בָּאוֹטוֹבּוּס",
  "בחצר": "בֶּחָצֵר",
  "בכיתה": "בַּכִּיתָה",
  "במטבח": "בַּמִּטְבָּח",
  "במפה": "בְּמַפָּה",
  "במשפט": "בַּמִּשְׁפָּט",
  "בננות": "בָּנָנוֹת",
  "בספריה": "בַּסִּפְרִיָּה",
  "בפארק": "בַּפַּארְק",
  "בקצה": "בַּקָּצֶה",
  "בשקט": "בְּשֶׁקֶט",
  "בתוך": "בְּתוֹךְ",
  "גררו": "גִּרְרוּ",
  "האוכל": "הָאֹכֶל",
  "הארוחה": "הָאֲרוּחָה",
  "הדפים": "הַדַּפִּים",
  "הדרך": "הַדֶּרֶךְ",
  "ההוראות": "הַהוֹרָאוֹת",
  "ההפסקה": "הַהַפְסָקָה",
  "ההצגה": "הַהַצָּגָה",
  "הווילון": "הַוִּילוֹן",
  "הולכים": "הוֹלְכִים",
  "הולכת": "הוֹלֶכֶת",
  "הולכות": "הוֹלְכוֹת",
  "החברות": "הַחֲבֵרוֹת",
  "החברים": "הַחֲבֵרִים",
  "החדש": "הֶחָדָשׁ",
  "החוקר": "הַחוֹקֵר",
  "החלון": "הַחַלּוֹן",
  "החתול": "הֶחָתוּל",
  "הטיול": "הַטִּיּוּל",
  "הילד": "הַיֶּלֶד",
  "הילדה": "הַיַּלְדָה",
  "הילדים": "הַיְלָדִים",
  "הכדור": "הַכַּדּוּר",
  "הכוס": "הַכּוֹס",
  "הכיסא": "הַכִּסֵּא",
  "הכיסאות": "הַכִּסְאוֹת",
  "הכלב": "הַכֶּלֶב",
  "הלוח": "הַלּוּחַ",
  "הלימודים": "הַלִּמּוּדִים",
  "הלך": "הָלַךְ",
  "המדף": "הַמַּדָּף",
  "המורה": "הַמּוֹרָה",
  "המילים": "הַמִּלִּים",
  "המטבח": "הַמִּטְבָּח",
  "המים": "הַמַּיִם",
  "המסקנה": "הַמַּסְקָנָה",
  "המפה": "הַמַּפָּה",
  "המשפחה": "הַמִּשְׁפָּחָה",
  "המשפט": "הַמִּשְׁפָּט",
  "הנהר": "הַנָּהָר",
  "הנכון": "הַנָּכוֹן",
  "הנכונה": "הַנְּכוֹנָה",
  "הספה": "הַסַּפָּה",
  "הספר": "הַסֵּפֶר",
  "הספרים": "הַסְּפָרִים",
  "הקבוצה": "הַקְּבוּצָה",
  "הקשיבה": "הִקְשִׁיבָה",
  "הרצפה": "הָרִצְפָּה",
  "השולחן": "הַשֻּׁלְחָן",
  "השינה": "הַשֵּׁנָה",
  "השיעור": "הַשִּׁעוּר",
  "השלטים": "הַשְּׁלָטִים",
  "השלימו": "הַשְׁלִימוּ",
  "התוצאות": "הַתּוֹצָאוֹת",
  "התיק": "הַתִּיק",
  "התיקים": "הַתִּיקִים",
  "התלמידים": "הַתַּלְמִידִים",
  "ו": "וְ",
  "ואז": "וְאָז",
  "ובננות": "וּבָנָנוֹת",
  "וגדעון": "וְגִדְעוֹן",
  "ובוחרת": "וּבוֹחֶרֶת",
  "וכתבה": "וְכָתְבָה",
  "וכותב": "וְכוֹתֵב",
  "ויוסי": "וְיוֹסִי",
  "ויעל": "וְיַעֵל",
  "ויושבים": "וְיוֹשְׁבִים",
  "ולשים": "וְלָשִׂים",
  "ומביאה": "וּמְבִיאָה",
  "ומסבירה": "וּמַסְבִּירָה",
  "ומוצאים": "וּמוֹצְאִים",
  "ומטאטאים": "וּמְטַאֲטְאִים",
  "ומניחה": "וּמַנִּיחָה",
  "ומסדרים": "וּמְסַדְּרִים",
  "זורק": "זוֹרֵק",
  "זורקים": "זוֹרְקִים",
  "זורקת": "זוֹרֶקֶת",
  "חוזרים": "חוֹזְרִים",
  "חוזר": "חוֹזֵר",
  "חוזרת": "חוֹזֶרֶת",
  "חוזרות": "חוֹזְרוֹת",
  "חילקה": "חִלְּקָה",
  "טובה": "טוֹבָה",
  "טובים": "טוֹבִים",
  "טסות": "טָסוֹת",
  "טסים": "טָסִים",
  "זה": "זֶה",
  "ידיים": "יָדַיִם",
  "יוצא": "יוֹצֵא",
  "יושב": "יוֹשֵׁב",
  "יושבים": "יוֹשְׁבִים",
  "יחד": "יַחַד",
  "ישב": "יָשַׁב",
  "ישן": "יָשֵׁן",
  "ישנים": "יְשֵׁנִים",
  "יוסי": "יוֹסִי",
  "יעל": "יַעֵל",
  "כבדים": "כְּבֵדִים",
  "כדאי": "כְּדַאי",
  "כדי": "כְּדֵי",
  "גדולה": "גְּדוֹלָה",
  "גדולים": "גְּדוֹלִים",
  "גדולות": "גְּדוֹלוֹת",
  "כותב": "כּוֹתֵב",
  "כותבת": "כּוֹתֶבֶת",
  "כי": "כִּי",
  "כתבה": "כָּתְבָה",
  "לאכול": "לֶאֱכֹל",
  "לאחיה": "לְאַחֶיהָ",
  "לבית": "לְבֵית",
  "הביתה": "הַבַּיְתָה",
  "להרים": "לְהָרִים",
  "לוקחת": "לוֹקַחַת",
  "לטיול": "לְטִיּוּל",
  "ליד": "לְיַד",
  "לכיתה": "לַכִּיתָה",
  "למקום": "לַמָּקוֹם",
  "למצוא": "לִמְצֹא",
  "לפארק": "לַפַּארְק",
  "לצייר": "לְצַיֵּר",
  "לקפוץ": "לִקְפֹּץ",
  "לרוץ": "לָרוּץ",
  "לשיעור": "לַשִּׁעוּר",
  "לשיר": "לָשִׁיר",
  "מביאה": "מְבִיאָה",
  "מבשלים": "מְבַשְּׁלִים",
  "מגלים": "מְגַלִּים",
  "מדברים": "מְדַבְּרִים",
  "מודד": "מוֹדֵד",
  "מול": "מוּל",
  "מוצאים": "מוֹצְאִים",
  "מוצאת": "מוֹצֵאת",
  "מטאטאים": "מְטַאֲטְאִים",
  "מטפס": "מְטַפֵּס",
  "מטפסת": "מְטַפֶּסֶת",
  "מכבסים": "מְכַבְּסִים",
  "מכין": "מֵכִין",
  "מכינה": "מְכִינָה",
  "מכינים": "מְכִינִים",
  "מניחה": "מַנִּיחָה",
  "מנפחת": "מְנַפַּחַת",
  "מנקה": "מְנַקָּה",
  "מנקים": "מְנַקִּים",
  "מסדרים": "מְסַדְּרִים",
  "מספרת": "מְסַפֶּרֶת",
  "מסתירה": "מַסְתִּירָה",
  "מעלים": "מַעֲלִים",
  "מצחצחים": "מְצַחְצְחִים",
  "מצייר": "מְצַיֵּר",
  "מציירות": "מְצַיְּרוֹת",
  "מציירים": "מְצַיְּרִים",
  "מציירת": "מְצַיֶּרֶת",
  "מקשיבים": "מַקְשִׁיבִים",
  "מרימה": "מְרִימָה",
  "מרימות": "מְרִימוֹת",
  "מרימים": "מְרִימִים",
  "משאירה": "מַשְׁאִירָה",
  "משחקים": "מְשַׂחֲקִים",
  "משתמשים": "מִשְׁתַּמְּשִׁים",
  "מתחת": "מִתַּחַת",
  "נוגה": "נוֹגָהּ",
  "נוסעים": "נוֹסְעִים",
  "נועה": "נוֹעָה",
  "נכנסים": "נִכְנָסִים",
  "נמצא": "נִמְצָא",
  "סוגר": "סוֹגֵר",
  "סוגרת": "סוֹגֶרֶת",
  "עובדים": "עוֹבְדִים",
  "עושים": "עוֹשִׂים",
  "עם": "עִם",
  "פותח": "פּוֹתֵחַ",
  "פותחת": "פּוֹתַחַת",
  "פתרון": "פִּתְרוֹן",
  "צובעים": "צוֹבְעִים",
  "צלחת": "צַלַּחַת",
  "ציירה": "צִיְּרָה",
  "קוטפת": "קוֹטֶפֶת",
  "קונה": "קוֹנָה",
  "קופץ": "קוֹפֵץ",
  "קופצים": "קוֹפְצִים",
  "קופצת": "קוֹפֶצֶת",
  "קורא": "קוֹרֵא",
  "קוראים": "קוֹרְאִים",
  "קוראת": "קוֹרֵאת",
  "קוראות": "קוֹרְאוֹת",
  "קרה": "קָרָה",
  "קפץ": "קָפַץ",
  "קראה": "קָרְאָה",
  "קרים": "קָרִים",
  "רוקדים": "רוֹקְדִים",
  "רושם": "רוֹשֵׁם",
  "רעיונות": "רַעְיוֹנוֹת",
  "רעש": "רַעַשׁ",
  "רץ": "רָץ",
  "רצים": "רָצִים",
  "שהמשימה": "שֶׁהַמְּשִׂימָה",
  "שהתברר": "שֶׁהִתְבָּרֵר",
  "שובר": "שׁוֹבֵר",
  "שוברות": "שׁוֹבְרוֹת",
  "שוברים": "שׁוֹבְרִים",
  "שוברת": "שׁוֹבֶרֶת",
  "שוחה": "שָׂחָה",
  "שוחים": "שָׂחִים",
  "שוטף": "שׁוֹטֵף",
  "שוטפים": "שׁוֹטְפִים",
  "שומע": "שׁוֹמֵעַ",
  "שומעת": "שׁוֹמַעַת",
  "שרות": "שָׁרוֹת",
  "שורק": "שׁוֹרֵק",
  "שותה": "שׁוֹתָה",
  "שלו": "שֶׁלּוֹ",
  "שלנו": "שֶׁלָּנוּ",
  "שמעה": "שָׁמְעָה",
  "שמח": "שָׂמֵחַ",
  "שמחה": "שְׂמֵחָה",
  "שמחים": "שְׂמֵחִים",
  "שמחות": "שְׂמֵחוֹת",
  "שקטה": "שְׁקֵטָה",
  "שרים": "שָׁרִים",
  "תולים": "תּוֹלִים",
  "תפוחים": "תַּפּוּחִים",
  "אדם": "אָדָם",
  "אוכלת": "אוֹכֶלֶת",
  "אוספים": "אוֹסְפִים",
  "אות": "אוֹת",
  "באמצע": "בָּאֶמְצַע",
  "בדרך": "בַּדֶּרֶךְ",
  "בודק": "בּוֹדֵק",
  "ביקשה": "בִּיקְּשָׁה",
  "בכדור": "בַּכַּדּוּר",
  "במה": "בַּמָּה",
  "במחברת": "בַּמַּחְבֶּרֶת",
  "במיטה": "בַּמִּטָּה",
  "במכונית": "בַּמְּכוֹנִית",
  "בסוף": "בַּסּוֹף",
  "ברורה": "בְּרוּרָה",
  "ברכה": "בְּרָכָה",
  "בתחילת": "בִּתְחִלַּת",
  "הבנות": "הַבָּנוֹת",
  "הבנים": "הַבָּנִים",
  "הדלת": "הַדֶּלֶת",
  "הולך": "הוֹלֵךְ",
  "הילדות": "הַיְלָדוֹת",
  "המחברות": "הַמַּחְבָּרוֹת",
  "המשחק": "הַמִּשְׂחָק",
  "המשימה": "הַמְּשִׂימָה",
  "הצלחות": "הַצְּלָחוֹת",
  "הקצרה": "הַקְּצָרָה",
  "ואוכלים": "וְאוֹכְלִים",
  "ואחותו": "וְאֲחוֹתוֹ",
  "וכותבים": "וְכוֹתְבִים",
  "וכיסא": "וְכִסֵּא",
  "ולחם": "וְלֶחֶם",
  "ומדויק": "וּמְדוּיָּק",
  "ומיץ": "וְמִיץ",
  "ומכינים": "וּמְכִינִים",
  "וספר": "וְסֵפֶר",
  "ועפרון": "וְעִפָּרוֹן",
  "וראתה": "וְרָאֲתָה",
  "יונתן": "יוֹנָתָן",
  "יוצאת": "יוֹצֵאת",
  "כותבים": "כּוֹתְבִים",
  "כך": "כָּךְ",
  "קטע": "קֶטַע",
  "קריאה": "קְרִיאָה",
  "קצר": "קָצָר",
  "להוראות": "לַהוֹרָאוֹת",
  "לוקח": "לוֹקֵחַ",
  "לחדר": "לַחֶדֶר",
  "לכאן": "לְכָאן",
  "לכיסא": "לַכִּסֵּא",
  "למטבח": "לַמִּטְבָּח",
  "לענות": "לַעֲנוֹת",
  "לפתור": "לִפְתֹּר",
  "לקרוא": "לִקְרֹא",
  "מהתלמידים": "מֵהַתַּלְמִידִים",
  "מוציאה": "מוֹצִיאָה",
  "מידע": "מֵידָע",
  "מילה": "מִלָּה",
  "מכתב": "מִכְתָּב",
  "מסקנה": "מַסְקָנָה",
  "מתחילים": "מַתְחִילִים",
  "נסעה": "נָסְעָה",
  "ציפורים": "צִפּוֹרִים",
  "רואה": "רוֹאָה",
  "שותים": "שׁוֹתִים",
};

const HEBREW_MULTI_WORD_NIKKUD_OVERRIDES = Array.from(
  new Map(
    [...Object.entries(HEBREW_NIKKUD_OVERRIDES), ...Object.entries(HEBREW_SENTENCE_NIKKUD_OVERRIDES)].filter(
      ([source]) => /\s/.test(source)
    )
  ).entries()
).sort((left, right) => right[0].length - left[0].length);

const HEBREW_WRITING_LETTERS = [
  "א",
  "ב",
  "ג",
  "ד",
  "ה",
  "ו",
  "ז",
  "ח",
  "ט",
  "י",
  "כ",
  "ל",
  "מ",
  "נ",
  "ס",
  "ע",
  "פ",
  "צ",
  "ק",
  "ר",
  "ש",
  "ת",
];

const HEBREW_WRITING_WORD_FALLBACKS = [
  "אמא",
  "אבא",
  "בית",
  "מים",
  "שלום",
  "חתול",
  "כלב",
  "ספר",
  "חבר",
  "ילדה",
  "ילד",
  "כדור",
  "חלון",
  "דלת",
  "שולחן",
  "משפחה",
];

const HEBREW_WRITING_SHORT_SENTENCES = [
  "אני אוהב לקרוא ספר.",
  "הילדה שותה מים.",
  "אמא מכינה ארוחת ערב.",
  "הילדים משחקים בחצר.",
  "המורה כותבת על הלוח.",
  "הכלב ישן ליד הדלת.",
  "אנחנו הולכים לבית הספר.",
  "החתול קופץ על הכיסא.",
];

const HEBREW_WRITING_LONG_SENTENCES = [
  "בתחילת השיעור הילדים מסדרים את המחברות על השולחן.",
  "לפני הארוחה אנחנו שוטפים ידיים ומכינים את הצלחות.",
  "התלמידים מקשיבים להוראות ואז מתחילים לפתור את המשימה.",
  "גבריאל בודק את המפה כדי למצוא את הדרך הקצרה לפארק.",
  "המשפחה נסעה לטיול קצר וראתה ציפורים ליד הנהר.",
  "נוגה קוראת סיפור מעניין ומסבירה לאחיה מה קרה.",
  "החברים אוספים מידע חדש וכותבים יחד מסקנה ברורה.",
  "המורה ביקשה מהתלמידים לענות במשפט מלא ומדויק.",
];

const HEBREW_WRITING_MEDIUM_SENTENCES = [
  "אחרי הפגישה אנחנו מסכמים את הרעיונות החשובים במחברת.",
  "המדריכה מסבירה איך להגיע לתחנה המרכזית בלי למהר.",
  "כשהגשם התחזק המשפחה חיפשה מקום יבש לשבת בו.",
  "לפני היציאה כדאי לבדוק שהטלפון, המפתחות והארנק בתיק.",
  "התלמידים משווים בין שתי תשובות ובוחרים את ההסבר המדויק יותר.",
  "בסוף היום אני מעדיף להכין רשימה קצרה של הדברים למחר.",
  "השכנים הזמינו אותנו לארוחת ערב חגיגית במרפסת.",
  "הצוות תכנן מסלול בטוח כדי להגיע בזמן לפגישה.",
];

const HEBREW_WRITING_ADVANCED_SENTENCES = [
  "למרות העייפות, היא המשיכה לקרוא את ההוראות עד שהבינה בדיוק מה צריך לעשות.",
  "במהלך הוויכוח כולם דיברו מהר מדי, ולכן היה קשה להבין את הנקודה העיקרית.",
  "אם נשמור קבלות ונרשום הוצאות, יהיה קל יותר לתכנן את התקציב לחודש הבא.",
  "אחרי שהמכשיר הפסיק לעבוד, בדקנו את הכבל, החלפנו סוללה וניסינו שוב.",
  "המורה ביקשה מכל תלמיד להסביר לא רק מה התשובה, אלא גם איך הגיע אליה.",
  "בזמן הנסיעה דיברנו על המקומות שנרצה לבקר בהם ועל הדברים שנצטרך לקחת.",
  "כדי למנוע בלבול, המנהלת חילקה משימות ברורות וקבעה מי אחראי על כל חלק.",
  "כאשר השכן הציע עזרה, הודינו לו וביקשנו שיחכה כמה דקות ליד הדלת.",
];

const HEBREW_AGREEMENT_BLUEPRINTS = [
  {
    difficulty: 1,
    displayText: "הילד קטן. ___ שמח.",
    options: ["הוא", "היא", "הם", "הן"],
    answer: "הוא",
    reviewText: "הילד קטן. הוא שמח.",
  },
  {
    difficulty: 1,
    displayText: "הילדה קוראת. ___ שקטה.",
    options: ["הוא", "היא", "הם", "הן"],
    answer: "היא",
    reviewText: "הילדה קוראת. היא שקטה.",
  },
  {
    difficulty: 1,
    displayText: "הילד ___.",
    options: ["גדול", "גדולה", "גדולים", "גדולות"],
    answer: "גדול",
    reviewText: "הילד גדול.",
  },
  {
    difficulty: 1,
    displayText: "הילדה ___.",
    options: ["גדול", "גדולה", "גדולים", "גדולות"],
    answer: "גדולה",
    reviewText: "הילדה גדולה.",
  },
  {
    difficulty: 2,
    displayText: "אבא ___ לבית.",
    options: ["הולך", "הולכת", "הולכים", "הולכות"],
    answer: "הולך",
    reviewText: "אבא הולך לבית.",
  },
  {
    difficulty: 2,
    displayText: "אמא ___ ספר.",
    options: ["קורא", "קוראת", "קוראים", "קוראות"],
    answer: "קוראת",
    reviewText: "אמא קוראת ספר.",
  },
  {
    difficulty: 2,
    displayText: "הילדים ___.",
    options: ["גדול", "גדולה", "גדולים", "גדולות"],
    answer: "גדולים",
    reviewText: "הילדים גדולים.",
  },
  {
    difficulty: 2,
    displayText: "הילדות ___.",
    options: ["גדול", "גדולה", "גדולים", "גדולות"],
    answer: "גדולות",
    reviewText: "הילדות גדולות.",
  },
  {
    difficulty: 3,
    displayText: "הילדים ___ לבית הספר.",
    options: ["הולך", "הולכת", "הולכים", "הולכות"],
    answer: "הולכים",
    reviewText: "הילדים הולכים לבית הספר.",
  },
  {
    difficulty: 3,
    displayText: "הילדות ___ לבית.",
    options: ["הולך", "הולכת", "הולכים", "הולכות"],
    answer: "הולכות",
    reviewText: "הילדות הולכות לבית.",
  },
  {
    difficulty: 3,
    displayText: "הבנים ___ ספר.",
    options: ["קורא", "קוראת", "קוראים", "קוראות"],
    answer: "קוראים",
    reviewText: "הבנים קוראים ספר.",
  },
  {
    difficulty: 3,
    displayText: "הבנות ___ ספר.",
    options: ["קורא", "קוראת", "קוראים", "קוראות"],
    answer: "קוראות",
    reviewText: "הבנות קוראות ספר.",
  },
  {
    difficulty: 4,
    displayText: "דני ויוסי ___ לשיעור.",
    options: ["חוזר", "חוזרת", "חוזרים", "חוזרות"],
    answer: "חוזרים",
    reviewText: "דני ויוסי חוזרים לשיעור.",
  },
  {
    difficulty: 4,
    displayText: "נועה ויעל ___ הביתה.",
    options: ["חוזר", "חוזרת", "חוזרים", "חוזרות"],
    answer: "חוזרות",
    reviewText: "נועה ויעל חוזרות הביתה.",
  },
  {
    difficulty: 5,
    displayText: "הילדים משחקים. ___ שמחים.",
    options: ["הוא", "היא", "הם", "הן"],
    answer: "הם",
    reviewText: "הילדים משחקים. הם שמחים.",
  },
  {
    difficulty: 5,
    displayText: "הילדות שרות. ___ שמחות.",
    options: ["הוא", "היא", "הם", "הן"],
    answer: "הן",
    reviewText: "הילדות שרות. הן שמחות.",
  },
  {
    difficulty: 6,
    displayText: "הספרים החדשים ___ על המדף.",
    options: ["נמצא", "נמצאת", "נמצאים", "נמצאות"],
    answer: "נמצאים",
    reviewText: "הספרים החדשים נמצאים על המדף.",
  },
  {
    difficulty: 6,
    displayText: "שתי החברות ___ ליציאה.",
    options: ["מוכן", "מוכנה", "מוכנים", "מוכנות"],
    answer: "מוכנות",
    reviewText: "שתי החברות מוכנות ליציאה.",
  },
  {
    difficulty: 7,
    displayText: "הילדות קיבלו ספרים חדשים, ו___ מיד התחילו לקרוא.",
    options: ["הוא", "היא", "הם", "הן"],
    answer: "הן",
    reviewText: "הילדות קיבלו ספרים חדשים, והן מיד התחילו לקרוא.",
  },
  {
    difficulty: 7,
    displayText: "הכיסאות בחדר ___ ליד הקיר.",
    options: ["עומד", "עומדת", "עומדים", "עומדות"],
    answer: "עומדים",
    reviewText: "הכיסאות בחדר עומדים ליד הקיר.",
  },
  {
    difficulty: 8,
    displayText: "המזוודות הכבדות ___ ליד הדלת עד הבוקר.",
    options: ["נשאר", "נשארה", "נשארו", "נשארתי"],
    answer: "נשארו",
    reviewText: "המזוודות הכבדות נשארו ליד הדלת עד הבוקר.",
  },
  {
    difficulty: 8,
    displayText: "ההחלטה הסופית ___ ברורה לכולם.",
    options: ["היה", "הייתה", "היו", "הייתי"],
    answer: "הייתה",
    reviewText: "ההחלטה הסופית הייתה ברורה לכולם.",
  },
  {
    difficulty: 9,
    displayText: "כשדנה ורות יצאו מהכיתה, ___ לקחו איתן את המחברות.",
    options: ["הוא", "היא", "הם", "הן"],
    answer: "הן",
    reviewText: "כשדנה ורות יצאו מהכיתה, הן לקחו איתן את המחברות.",
  },
  {
    difficulty: 9,
    displayText: "המסמכים החשובים ___ מוכנים לחתימה.",
    options: ["היה", "הייתה", "היו", "הייתי"],
    answer: "היו",
    reviewText: "המסמכים החשובים היו מוכנים לחתימה.",
  },
  {
    difficulty: 10,
    displayText: "אם ההנחיות החדשות ___ ברורות, אפשר להתחיל לעבוד.",
    options: ["אינו", "אינה", "אינם", "אינן"],
    answer: "אינן",
    reviewText: "אם ההנחיות החדשות אינן ברורות, אפשר להתחיל לעבוד.",
  },
  {
    difficulty: 10,
    displayText: "הצוות והשכנים ___ אחראים על הסידור בחצר.",
    options: ["אחראי", "אחראית", "אחראים", "אחראיות"],
    answer: "אחראים",
    reviewText: "הצוות והשכנים אחראים על הסידור בחצר.",
  },
];

const HEBREW_CATEGORY_SORT_GROUPS = [
  {
    label: "אוכל",
    words: ["תַּפּוּחַ", "לֶחֶם", "בָּנָנָה", "חָלָב", "עוּגָה", "גְּבִינָה", "אוֹרֶז", "עַגְבָנִיָּה", "לִימוֹן", "תֵּה"],
  },
  {
    label: "חיות",
    words: ["כֶּלֶב", "חָתוּל", "צִפּוֹר", "דָּג", "נְמָלָה", "עַכָּבִישׁ", "יַתּוּשׁ", "סוּס", "פָּרָה", "אַרְנָב"],
  },
  {
    label: "בית ספר",
    words: ["סֵפֶר", "מַחְבֶּרֶת", "עֵט", "עִפָּרוֹן", "כִּסֵּא", "כִּיתָּה", "מוֹרָה", "שֻׁלְחָן", "יַלְקוּט", "לוּחַ"],
  },
  {
    label: "צבעים",
    words: ["כָּחוֹל", "אָדוֹם", "צָהוֹב", "כָּתוֹם", "שָׁחֹר", "לָבָן", "יָרוֹק", "וָרוֹד", "סָגוֹל", "חוּם"],
  },
  {
    label: "מטבח",
    words: ["כַּף", "צַלַּחַת", "כּוֹס", "מְקָרֵר", "תַּנּוּר", "קְעָרָה", "סַכִּין", "מַזְלֵג", "סִיר", "מַפִּית"],
  },
  {
    label: "בגדים",
    words: ["חוּלְצָה", "מִכְנָסַיִם", "נַעֲלַיִם", "כּוֹבַע", "גַּרְבַּיִם", "מְעִיל", "שִׂמְלָה", "חֲצָאִית", "חֲגוֹרָה", "סַנְדָּל"],
  },
  {
    label: "חלקי גוף",
    words: ["רֹאשׁ", "יָד", "רֶגֶל", "עַיִן", "אַף", "פֶּה", "אֹזֶן", "בֶּטֶן", "לֵב", "שֵׂעָר"],
  },
  {
    label: "תחבורה",
    words: ["מְכוֹנִית", "אוֹטוֹבּוּס", "רַכֶּבֶת", "אוֹפַנַּיִם", "מָטוֹס", "סְפִינָה", "מַשָּׂאִית", "מוֹנִית", "טְרַקְטוֹר", "אֶמְבּוּלַנְס"],
  },
  {
    label: "מזג אוויר",
    words: ["שֶׁמֶשׁ", "גֶּשֶׁם", "רוּחַ", "עָנָן", "שֶׁלֶג", "בָּרָק", "קֶשֶׁת", "חוֹם", "קוֹר", "סְעָרָה"],
  },
  {
    label: "טבע",
    words: ["עֵץ", "פֶּרַח", "דֶּשֶׁא", "עָלֶה", "אֶבֶן", "הַר", "נָהָר", "יָם", "חוֹל", "יָעַר"],
  },
  {
    label: "צעצועים",
    words: ["כַּדּוּר", "בּוּבָּה", "פָּאזֶל", "קֻבִּיָּה", "דּוּבִּי", "עֲפִיפוֹן", "בַּלּוֹן", "תּוֹף", "רוֹבּוֹט", "קַלָּפִים"],
  },
  {
    label: "משפחה",
    words: ["אִמָּא", "אַבָּא", "אָח", "אָחוֹת", "סַבָּא", "סָבְתָּא", "תִּינוֹק", "דּוֹד", "דּוֹדָה", "יֶלֶד", "יַלְדָּה"],
  },
  {
    label: "חדר אמבטיה",
    words: [
      "סַבּוֹן",
      "מַגֶּבֶת",
      "מִבְרֶשֶׁת שִׁנַּיִם",
      "שַׁמְפּוֹ",
      "כִּיּוֹר",
      "אַמְבַּטְיָה",
      "מַרְאָה",
      "בְּרָז",
      "אַסְלָה",
      "מִשְׁחַת שִׁנַּיִם",
    ],
  },
  {
    label: "רגשות",
    words: ["שמחה", "תקווה", "סקרנות", "התרגשות", "דאגה", "שלווה", "אהבה", "כעס", "פחד", "הפתעה"],
  },
  {
    label: "עיר",
    words: ["רחוב", "כיכר", "תחנה", "חנות", "משרד", "מרפאה", "ספריה", "שכונה", "גשר", "מעלית"],
  },
  {
    label: "תקשורת",
    words: ["הודעה", "שיחה", "תשובה", "שאלה", "כתובת", "טלפון", "אתר", "תמונה", "מסך", "מצלמה"],
  },
  {
    label: "עבודה ולימודים",
    words: ["פגישה", "משימה", "פרויקט", "צוות", "אחריות", "ניסיון", "החלטה", "מסמך", "דיווח", "מחקר"],
  },
  {
    label: "זמן",
    words: ["שבוע", "חודש", "שנה", "דקה", "רגע", "תקופה", "תאריך", "הפסקה", "התחלה", "סוף"],
  },
  {
    label: "בית",
    words: ["סלון", "מרפסת", "מדרגות", "מפתח", "ארנק", "ארון", "מדף", "שמיכה", "כרית", "מנורה"],
  },
  {
    label: "בריאות",
    words: ["כאב", "תרופה", "מרשם", "בדיקה", "מנוחה", "נשימה", "בריאות", "תיאבון", "חום", "סחרחורת"],
  },
  {
    label: "נסיעה",
    words: ["כרטיס", "מזוודה", "דרכון", "טיסה", "מסלול", "עיכוב", "נהג", "תחנה", "נסיעה", "כיוון"],
  },
];

const HEBREW_CATEGORY_SORT_LEVEL_CONFIG = {
  1: { labelPool: ["אוכל", "חיות", "צבעים", "צעצועים"], bucketCount: 2, itemsPerBucket: 2 },
  2: { labelPool: ["אוכל", "חיות", "בית ספר", "צבעים", "מטבח", "בגדים", "משפחה"], bucketCount: 3, itemsPerBucket: 2 },
  3: {
    labelPool: ["אוכל", "חיות", "בית ספר", "צבעים", "מטבח", "בגדים", "חלקי גוף", "משפחה", "צעצועים", "טבע"],
    bucketCount: 3,
    itemsPerBucket: 2,
  },
  4: {
    labelPool: ["אוכל", "חיות", "בית ספר", "צבעים", "מטבח", "בגדים", "חלקי גוף", "תחבורה", "מזג אוויר", "טבע", "צעצועים", "משפחה"],
    bucketCount: 4,
    itemsPerBucket: 2,
  },
  5: {
    labelPool: [
      "אוכל",
      "חיות",
      "בית ספר",
      "צבעים",
      "מטבח",
      "בגדים",
      "חלקי גוף",
      "תחבורה",
      "מזג אוויר",
      "טבע",
      "צעצועים",
      "משפחה",
      "חדר אמבטיה",
    ],
    bucketCount: 5,
    itemsPerBucket: 2,
  },
  6: {
    labelPool: ["אוכל", "חיות", "בית ספר", "מטבח", "משפחה", "בית", "זמן", "עיר", "תקשורת", "רגשות"],
    bucketCount: 5,
    itemsPerBucket: 3,
  },
  7: {
    labelPool: ["אוכל", "בית ספר", "משפחה", "בית", "זמן", "עיר", "תקשורת", "עבודה ולימודים", "רגשות", "בריאות"],
    bucketCount: 5,
    itemsPerBucket: 3,
  },
  8: {
    labelPool: ["אוכל", "בית", "זמן", "עיר", "תקשורת", "עבודה ולימודים", "רגשות", "בריאות", "נסיעה", "תחבורה", "מזג אוויר"],
    bucketCount: 6,
    itemsPerBucket: 3,
  },
  9: {
    labelPool: ["בית", "זמן", "עיר", "תקשורת", "עבודה ולימודים", "רגשות", "בריאות", "נסיעה", "תחבורה", "מזג אוויר", "טבע"],
    bucketCount: 6,
    itemsPerBucket: 4,
  },
  10: {
    labelPool: ["בית", "זמן", "עיר", "תקשורת", "עבודה ולימודים", "רגשות", "בריאות", "נסיעה", "תחבורה", "מזג אוויר", "טבע", "חדר אמבטיה"],
    bucketCount: 7,
    itemsPerBucket: 4,
  },
};

const HEBREW_FINAL_LETTER_DRILLS = [
  { difficulty: 1, middleLetter: "כ", finalLetter: "ך", middleWord: "מכונית", finalWord: "נמוך" },
  { difficulty: 1, middleLetter: "מ", finalLetter: "ם", middleWord: "ימינה", finalWord: "לחם" },
  { difficulty: 1, middleLetter: "נ", finalLetter: "ן", middleWord: "בננה", finalWord: "קטן" },
  { difficulty: 1, middleLetter: "פ", finalLetter: "ף", middleWord: "ציפור", finalWord: "חוף" },
  { difficulty: 1, middleLetter: "צ", finalLetter: "ץ", middleWord: "ביצה", finalWord: "עץ" },
  { difficulty: 2, middleLetter: "כ", finalLetter: "ך", middleWord: "מכתב", finalWord: "מלך" },
  { difficulty: 2, middleLetter: "מ", finalLetter: "ם", middleWord: "למעלה", finalWord: "אדום" },
  { difficulty: 2, middleLetter: "נ", finalLetter: "ן", middleWord: "גבינה", finalWord: "שעון" },
  { difficulty: 2, middleLetter: "פ", finalLetter: "ף", middleWord: "מלפפון", finalWord: "כסף" },
  { difficulty: 2, middleLetter: "צ", finalLetter: "ץ", middleWord: "חצי", finalWord: "מיץ" },
  { difficulty: 3, middleLetter: "כ", finalLetter: "ך", middleWord: "ברכה", finalWord: "דרך" },
  { difficulty: 3, middleLetter: "מ", finalLetter: "ם", middleWord: "שמאלה", finalWord: "חם" },
  { difficulty: 3, middleLetter: "נ", finalLetter: "ן", middleWord: "ענבים", finalWord: "לבן" },
  { difficulty: 3, middleLetter: "פ", finalLetter: "ף", middleWord: "מאפייה", finalWord: "אף" },
  { difficulty: 3, middleLetter: "צ", finalLetter: "ץ", middleWord: "קבוצה", finalWord: "קיץ" },
  { difficulty: 4, middleLetter: "כ", finalLetter: "ך", middleWord: "בריכה", finalWord: "תאריך" },
  { difficulty: 4, middleLetter: "מ", finalLetter: "ם", middleWord: "משימה", finalWord: "חלום" },
  { difficulty: 4, middleLetter: "נ", finalLetter: "ן", middleWord: "מנגינה", finalWord: "עניין" },
  { difficulty: 4, middleLetter: "פ", finalLetter: "ף", middleWord: "קפיצה", finalWord: "עוף" },
  { difficulty: 4, middleLetter: "צ", finalLetter: "ץ", middleWord: "מצלמה", finalWord: "ארץ" },
  { difficulty: 5, middleLetter: "כ", finalLetter: "ך", middleWord: "מכשיר", finalWord: "מסך" },
  { difficulty: 5, middleLetter: "מ", finalLetter: "ם", middleWord: "מצלמה", finalWord: "עולם" },
  { difficulty: 5, middleLetter: "נ", finalLetter: "ן", middleWord: "אנשים", finalWord: "רעיון" },
  { difficulty: 5, middleLetter: "פ", finalLetter: "ף", middleWord: "תפקיד", finalWord: "שותף" },
  { difficulty: 5, middleLetter: "צ", finalLetter: "ץ", middleWord: "מצב", finalWord: "חוץ" },
  { difficulty: 6, middleLetter: "כ", finalLetter: "ך", middleWord: "רכבת", finalWord: "צריך" },
  { difficulty: 6, middleLetter: "מ", finalLetter: "ם", middleWord: "מדרגה", finalWord: "צילום" },
  { difficulty: 6, middleLetter: "נ", finalLetter: "ן", middleWord: "מנורה", finalWord: "תכנון" },
  { difficulty: 6, middleLetter: "פ", finalLetter: "ף", middleWord: "תפקיד", finalWord: "ענף" },
  { difficulty: 6, middleLetter: "צ", finalLetter: "ץ", middleWord: "מציאות", finalWord: "לחץ" },
  { difficulty: 7, middleLetter: "כ", finalLetter: "ך", middleWord: "הצלחה", finalWord: "חינוך" },
  { difficulty: 7, middleLetter: "מ", finalLetter: "ם", middleWord: "תמרור", finalWord: "יוזם" },
  { difficulty: 7, middleLetter: "נ", finalLetter: "ן", middleWord: "תנועה", finalWord: "עניין" },
  { difficulty: 7, middleLetter: "פ", finalLetter: "ף", middleWord: "תקופה", finalWord: "אלף" },
  { difficulty: 7, middleLetter: "צ", finalLetter: "ץ", middleWord: "הצגה", finalWord: "אומץ" },
  { difficulty: 8, middleLetter: "כ", finalLetter: "ך", middleWord: "תוכנית", finalWord: "מהלך" },
  { difficulty: 8, middleLetter: "מ", finalLetter: "ם", middleWord: "משפחה", finalWord: "צילום" },
  { difficulty: 8, middleLetter: "נ", finalLetter: "ן", middleWord: "תחנה", finalWord: "עדכון" },
  { difficulty: 8, middleLetter: "פ", finalLetter: "ף", middleWord: "תקיפה", finalWord: "שיתוף" },
  { difficulty: 8, middleLetter: "צ", finalLetter: "ץ", middleWord: "מציאות", finalWord: "מרוץ" },
  { difficulty: 9, middleLetter: "כ", finalLetter: "ך", middleWord: "זכייה", finalWord: "תיווך" },
  { difficulty: 9, middleLetter: "מ", finalLetter: "ם", middleWord: "מדריכים", finalWord: "קידום" },
  { difficulty: 9, middleLetter: "נ", finalLetter: "ן", middleWord: "מנהיגות", finalWord: "שלטון" },
  { difficulty: 9, middleLetter: "פ", finalLetter: "ף", middleWord: "תפיסה", finalWord: "עדיף" },
  { difficulty: 9, middleLetter: "צ", finalLetter: "ץ", middleWord: "קבוצה", finalWord: "חפץ" },
  { difficulty: 10, middleLetter: "כ", finalLetter: "ך", middleWord: "מכולת", finalWord: "המשך" },
  { difficulty: 10, middleLetter: "מ", finalLetter: "ם", middleWord: "מסגרת", finalWord: "תיאום" },
  { difficulty: 10, middleLetter: "נ", finalLetter: "ן", middleWord: "תנאים", finalWord: "דיון" },
  { difficulty: 10, middleLetter: "פ", finalLetter: "ף", middleWord: "הפסקה", finalWord: "שקוף" },
  { difficulty: 10, middleLetter: "צ", finalLetter: "ץ", middleWord: "מצפון", finalWord: "אילוץ" },
];

const HEBREW_READING_BLUEPRINTS = [
  {
    difficulty: 1,
    lines: ["דנה אוכלת תפוח."],
    question: "מה דנה אוכלת?",
    options: ["תפוח", "ספר", "כדור", "מים"],
    answer: "תפוח",
    images: [{ asset: "apple.svg", alt: "תפוח" }],
  },
  {
    difficulty: 1,
    lines: ["הכלב רץ."],
    question: "מי רץ?",
    options: ["הכלב", "החתול", "הילד", "הספר"],
    answer: "הכלב",
    images: [{ asset: "dog.svg", alt: "כלב" }],
  },
  {
    difficulty: 2,
    lines: ["נועם שותה חלב.", "הכוס על השולחן."],
    question: "מה נועם שותה?",
    options: ["חלב", "מיץ", "מים", "תה"],
    answer: "חלב",
    images: [{ asset: "milk.svg", alt: "חלב" }],
  },
  {
    difficulty: 2,
    lines: ["מיה קוראת ספר.", "הספר חדש."],
    question: "מה מיה קוראת?",
    options: ["ספר", "עוגה", "כדור", "מיטה"],
    answer: "ספר",
    images: [{ asset: "book.svg", alt: "ספר" }],
  },
  {
    difficulty: 3,
    lines: ["אורי משחק בכדור.", "הכדור אדום."],
    question: "במה אורי משחק?",
    options: ["כדור", "ספר", "כיסא", "לחם"],
    answer: "כדור",
    images: [{ asset: "ball.svg", alt: "כדור" }],
  },
  {
    difficulty: 3,
    lines: ["יעל רואה חתול.", "החתול יושב על כיסא."],
    question: "איפה החתול יושב?",
    options: ["על כיסא", "במיטה", "במכונית", "על ספר"],
    answer: "על כיסא",
    images: [
      { asset: "cat.svg", alt: "חתול" },
      { asset: "chair.svg", alt: "כיסא" },
    ],
  },
  {
    difficulty: 4,
    lines: ["אמא מכינה עוגה.", "דנה מביאה צלחת.", "כולם יושבים במטבח."],
    question: "איפה כולם יושבים?",
    options: ["במטבח", "בחצר", "בכיתה", "באוטובוס"],
    answer: "במטבח",
    images: [{ asset: "cake.svg", alt: "עוגה" }],
  },
  {
    difficulty: 4,
    lines: ["יונתן לוקח ספר.", "הוא הולך לכיסא.", "אחר כך הוא קורא בשקט."],
    question: "מה יונתן לוקח?",
    options: ["ספר", "תפוח", "כדור", "דלת"],
    answer: "ספר",
    images: [
      { asset: "book.svg", alt: "ספר" },
      { asset: "chair.svg", alt: "כיסא" },
    ],
  },
  {
    difficulty: 5,
    lines: [
      "תמר יוצאת לבית הספר עם תיק וספר.",
      "בדרך היא רואה אוטובוס גדול.",
      "בכיתה היא מוציאה מחברת ועפרון.",
    ],
    question: "מה תמר מוציאה בכיתה?",
    options: ["מחברת ועפרון", "חלב ולחם", "כדור וכיסא", "עוגה ומיץ"],
    answer: "מחברת ועפרון",
    images: [
      { asset: "bag.svg", alt: "תיק" },
      { asset: "book.svg", alt: "ספר" },
      { asset: "notebook.svg", alt: "מחברת" },
    ],
  },
  {
    difficulty: 5,
    lines: [
      "אדם ואחותו הולכים למטבח אחרי המשחק.",
      "הם שותים מים ואוכלים תפוח.",
      "אחר כך הם חוזרים לחדר עם הספר החדש.",
    ],
    question: "מה הם עושים במטבח?",
    options: ["שותים מים ואוכלים תפוח", "נוסעים באוטובוס", "כותבים במחברת", "ישנים במיטה"],
    answer: "שותים מים ואוכלים תפוח",
    images: [
      { asset: "apple.svg", alt: "תפוח" },
      { asset: "book.svg", alt: "ספר" },
    ],
  },
  {
    difficulty: 6,
    lines: [
      "לפני היציאה נועם בדק שהטלפון, המפתחות והארנק בתיק שלו.",
      "אחר כך הוא נעל את הדלת וירד במדרגות.",
    ],
    question: "מה נועם בדק לפני היציאה?",
    options: [
      "שהטלפון, המפתחות והארנק בתיק שלו",
      "שהחלון פתוח",
      "שהאוכל מוכן",
      "שהאוטובוס הגיע",
    ],
    answer: "שהטלפון, המפתחות והארנק בתיק שלו",
    images: [],
  },
  {
    difficulty: 6,
    lines: [
      "רוני חיפשה תחנה קרובה לאוטובוס, אבל גילתה שהקו מתעכב.",
      "בינתיים היא התקשרה לחברה שלה כדי לעדכן אותה.",
    ],
    question: "למה רוני התקשרה לחברה שלה?",
    options: ["כדי לעדכן אותה", "כדי להזמין אוכל", "כדי לבטל שיעור", "כדי לקנות כרטיס"],
    answer: "כדי לעדכן אותה",
    images: [],
  },
  {
    difficulty: 7,
    lines: [
      "אמא ביקשה מעידו לקנות לחם, חלב ועגבניות.",
      "הוא מצא מבצע על גבינה אבל שכח לקחת ביצים.",
    ],
    question: "מה עידו שכח לקחת?",
    options: ["ביצים", "חלב", "לחם", "עגבניות"],
    answer: "ביצים",
    images: [],
  },
  {
    difficulty: 7,
    lines: [
      "כשהתחיל לרדת גשם, הקבוצה עברה לשבת במרפסת המקורה.",
      "המדריך פרש מפה חדשה והסביר איך ממשיכים במסלול.",
    ],
    question: "איפה הקבוצה ישבה כשירד גשם?",
    options: ["במרפסת המקורה", "בתחנה המרכזית", "ליד הנהר", "על הדשא"],
    answer: "במרפסת המקורה",
    images: [],
  },
  {
    difficulty: 8,
    lines: [
      "בפגישה הקצרה הצוות עבר על המשימות של השבוע הבא.",
      "יעל קיבלה אחריות על הדוח, ועומר בדק את לוח הזמנים.",
    ],
    question: "על מה יעל קיבלה אחריות?",
    options: ["על הדוח", "על המפתחות", "על האוכל", "על התחבורה"],
    answer: "על הדוח",
    images: [],
  },
  {
    difficulty: 8,
    lines: [
      "אחרי שהמחשב הפסיק לעבוד, דניאל ניסה להחליף כבל ולהפעיל אותו מחדש.",
      "כשזה לא עזר, הוא שלח הודעה לטכנאי וביקש שיגיע בהקדם.",
    ],
    question: "למי דניאל שלח הודעה?",
    options: ["לטכנאי", "לשכן", "למורה", "לנהג"],
    answer: "לטכנאי",
    images: [],
  },
  {
    difficulty: 9,
    lines: [
      "במהלך הנסיעה לירושלים כולם דיברו על המקומות שירצו לבקר בהם.",
      "בסוף החליטו להתחיל בשוק, להמשיך למוזיאון ולסיים בארוחת ערב.",
    ],
    question: "איפה הם החליטו להתחיל?",
    options: ["בשוק", "במוזיאון", "בתחנה", "במלון"],
    answer: "בשוק",
    images: [],
  },
  {
    difficulty: 9,
    lines: [
      "המנהלת חילקה את המשימה לחלקים ברורים כדי למנוע בלבול.",
      "כל תלמיד קיבל תפקיד אחר, ובסוף היום כולם הגישו סיכום מסודר.",
    ],
    question: "למה המנהלת חילקה את המשימה לחלקים?",
    options: ["כדי למנוע בלבול", "כדי לקצר את ההפסקה", "כדי לסגור את החצר", "כדי לשנות את המסלול"],
    answer: "כדי למנוע בלבול",
    images: [],
  },
  {
    difficulty: 10,
    lines: [
      "למרות העייפות, מאיה המשיכה לקרוא את ההוראות עד שהבינה בדיוק מה נדרש ממנה.",
      "רק אחרי שבדקה שוב את כל הפרטים היא שלחה את הקובץ הסופי.",
    ],
    question: "מתי מאיה שלחה את הקובץ הסופי?",
    options: [
      "אחרי שבדקה שוב את כל הפרטים",
      "לפני שקראה את ההוראות",
      "בזמן ההפסקה הראשונה",
      "כשחברתה התקשרה אליה",
    ],
    answer: "אחרי שבדקה שוב את כל הפרטים",
    images: [],
  },
  {
    difficulty: 10,
    lines: [
      "השכנים רצו לארגן אירוע קטן בחצר, אבל היה קשה לבחור תאריך שמתאים לכולם.",
      "בסופו של דבר הם פתחו קבוצה משותפת, הציעו שלוש אפשרויות והצביעו יחד.",
    ],
    question: "איך השכנים החליטו על התאריך?",
    options: [
      "הם פתחו קבוצה משותפת והצביעו על שלוש אפשרויות",
      "הם חיכו שהמזג ישתנה",
      "הם ביקשו מהנהג לבחור",
      "הם ביטלו את האירוע מיד",
    ],
    answer: "הם פתחו קבוצה משותפת והצביעו על שלוש אפשרויות",
    images: [],
  },
];

const SCIENCE_EXCLUDED_PATTERNS = [
  /north celestial pole/i,
  /Sputnik/i,
  /Rhinoplasty/i,
  /LASER/i,
  /thermodynamics/i,
  /belly button/i,
  /Apollo mission/i,
  /Curium/i,
  /Gregory Mendel/i,
  /synthesis of DNA/i,
  /bacterial pathogen/i,
];

