(() => {
const OPTION_LABELS = ["A", "B", "C", "D"];
const SESSION_HISTORY_STORAGE_KEY = "homework-session-history-v2";
const SELECTED_USER_STORAGE_KEY = "homework-selected-user-v1";
const GOOGLE_SHEETS_REPORT_WEB_APP_URL =
  "https://script.google.com/macros/s/AKfycbw3bO2JJBvAxy0m0iwxxz7oZeZuIznjt3jX977A9fU0St_YqOVxuKcr_OLWOcng9m5y0Q/exec";
const GOOGLE_SHEETS_REPORT_QUEUE_STORAGE_KEY = "homework-google-sheets-report-queue-v1";
const GOOGLE_SHEETS_REPORT_SOURCE = "kids_homework_app";
const GOOGLE_SHEETS_REPORT_SCHEMA_VERSION = 1;
const MAX_SAVED_SESSIONS = 10;
const QUESTION_COUNT_OPTIONS = [5, 10, 20, 30];
const SPEED_ROUND_QUESTION_COUNT = 5;
const SPEED_ROUND_SECONDS = 10;
const SPEED_ROUND_MS = SPEED_ROUND_SECONDS * 1000;
const ADULT_USER_ID = "miranda";
const ADULT_SESSION_DEFAULT_QUESTION_COUNT = 30;
const ADULT_MATH_INTERVAL = 2;
const ADULT_GEOGRAPHY_SHARE = 1 / 8;
const MAX_SESSION_DIFFICULTY = 10;
const FIXED_ADULT_SESSION_DIFFICULTY = MAX_SESSION_DIFFICULTY;
const DEFAULT_HEBREW_WRITING_TAIL_COUNT = 3;
const HEBREW_ONLY_WRITING_TAIL_COUNT = 5;
const RESERVED_MAP_CATEGORY = "geography-map";
const LANGUAGE_DRAG_INTERVAL = 4;
const HEBREW_FINAL_LETTER_INTERVAL = 14;
const HEBREW_IMAGE_DRAG_SHARE = 0.3;
const HEBREW_MATCHING_PAIR_COUNT = 4;
const HEBREW_OPPOSITES_PAIR_COUNT = 2;
const GENERATED_CATEGORY_DRAG_SHARES = {
  "reading-comprehension": 0.32,
  "vocabulary-grammar": 0.28,
  fractions: 0.28,
  "fractions-and-ratios": 0.24,
  science: 0.2,
  "financial-literacy": 0.18,
  nutrition: 0.22,
  "household-problem-solving": 0.34,
  estimation: 0.22,
  measurement: 0.26,
  "visual-measurement": 0.3,
  "maps-and-directions": 0.3,
  history: 0.58,
};
const HEBREW_OPPOSITE_PAIR_DEFINITIONS = [
  { leftEnglish: "A lot", rightEnglish: "A little", leftDisplay: "הַרְבֵּה", rightDisplay: "קְצָת" },
  { leftEnglish: "Good", rightEnglish: "Bad", leftDisplay: "טוֹב", rightDisplay: "רַע" },
  { leftEnglish: "Black", rightEnglish: "White", leftDisplay: "שָׁחוֹר", rightDisplay: "לָבָן" },
  { leftEnglish: "Hot", rightEnglish: "Cold", leftDisplay: "חַם", rightDisplay: "קַר" },
  { leftEnglish: "Up", rightEnglish: "Down", leftDisplay: "לְמַעְלָה", rightDisplay: "לְמַטָּה" },
  { leftEnglish: "Big", rightEnglish: "Small", leftDisplay: "גָּדוֹל", rightDisplay: "קָטָן" },
  { leftEnglish: "Cheap", rightEnglish: "Expensive", leftDisplay: "זוֹל", rightDisplay: "יָקָר" },
  { leftEnglish: "Open", rightEnglish: "Closed", leftDisplay: "פָּתוּחַ", rightDisplay: "סָגוּר" },
  { leftEnglish: "Fast", rightEnglish: "Slow", leftDisplay: "מָהִיר", rightDisplay: "אִטִּי" },
  { leftEnglish: "Healthy", rightEnglish: "Sick", leftDisplay: "בָּרִיא", rightDisplay: "חוֹלֶה" },
  { leftEnglish: "High", rightEnglish: "Low", leftDisplay: "גָּבֹהַּ", rightDisplay: "נָמוּךְ" },
  { leftEnglish: "Inside", rightEnglish: "Outside", leftDisplay: "בִּפְנִים", rightDisplay: "בַּחוּץ" },
  { leftEnglish: "New", rightEnglish: "Old (thing)", leftDisplay: "חָדָשׁ", rightDisplay: "יָשָׁן" },
  { leftEnglish: "Rich", rightEnglish: "Poor", leftDisplay: "עָשִׁיר", rightDisplay: "עָנִי" },
  {
    leftEnglish: "Right (direction)",
    rightEnglish: "Left (direction)",
    leftDisplay: "יָמִינָה",
    rightDisplay: "שְׂמֹאלָה",
  },
  { leftEnglish: "Strong", rightEnglish: "Weak", leftDisplay: "חָזָק", rightDisplay: "חַלָּשׁ" },
  { leftEnglish: "Beautiful", rightEnglish: "Ugly", leftDisplay: "יָפֶה", rightDisplay: "מְכֹעָר" },
  { leftEnglish: "Here", rightEnglish: "There", leftDisplay: "פֹּה", rightDisplay: "שָׁם" },
  { leftEnglish: "Early", rightEnglish: "Late", leftDisplay: "מֻקְדָּם", rightDisplay: "מְאֻחָר" },
  { leftEnglish: "Easy", rightEnglish: "Difficult", leftDisplay: "קַל", rightDisplay: "קָשֶׁה" },
  { leftEnglish: "First", rightEnglish: "Last, final", leftDisplay: "רִאשׁוֹן", rightDisplay: "אַחֲרוֹן" },
  { leftEnglish: "Long (m.s.)", rightEnglish: "Short (m.s.)", leftDisplay: "אָרוֹךְ", rightDisplay: "קָצָר" },
  { leftEnglish: "Near / next to", rightEnglish: "Far away", leftDisplay: "לְיַד", rightDisplay: "הַרְחֵק" },
  {
    leftEnglish: "Inside / interior / content",
    rightEnglish: "Outside of",
    leftDisplay: "תּוֹךְ",
    rightDisplay: "מִחוּץ",
  },
];
const REVIEW_FOCUS_SHARE = 0.2;
const REVIEW_RECENCY_DECAY = 0.82;
const SNAPSHOT_DATE_PATTERN = /^Snapshot date:\s*(\d{4}-\d{2}-\d{2})\.$/;
const CORE_SESSION_CATEGORIES = ["math", "hebrew"];
const NON_CORE_SESSION_CATEGORIES = [
  "addition-subtraction",
  "multiplication-division",
  "place-value-decimals",
  "geometry",
  "patterns-sequences",
  "coordinates-functions",
  "science",
  "science-evidence",
  "time",
  "statistics",
  "negative-numbers",
  "percentages",
  "algebra",
  "applied-word-problems",
  "visual-math",
  "visual-measurement",
  "logic",
  "rationality",
  "general-knowledge",
  "geography",
  "geography-map",
  "history",
  "population",
  "computing",
  "financial-literacy",
  "measurement",
  "charts-and-graphs",
  "calendar",
  "estimation",
  "probability",
  "reading-comprehension",
  "vocabulary-grammar",
  "maps-and-directions",
  "health-and-first-aid",
  "nutrition",
  "household-problem-solving",
  "fractions",
  "fractions-and-ratios",
  "spatial-reasoning",
];
const REVIEW_FOCUS_ALLOWED_CATEGORIES = new Set([
  "math",
  "addition-subtraction",
  "multiplication-division",
  "place-value-decimals",
  "geometry",
  "patterns-sequences",
  "coordinates-functions",
  "hebrew",
  "time",
  "statistics",
  "negative-numbers",
  "percentages",
  "algebra",
  "applied-word-problems",
  "visual-math",
  "visual-measurement",
  "measurement",
  "charts-and-graphs",
  "calendar",
  "estimation",
  "probability",
  "vocabulary-grammar",
  "maps-and-directions",
  "fractions",
  "fractions-and-ratios",
  "spatial-reasoning",
]);
const SESSION_CATEGORY_ORDER = [...CORE_SESSION_CATEGORIES, ...NON_CORE_SESSION_CATEGORIES];
const CORE_CATEGORY_SHARE = 0.45;

function createUniformCategoryDifficulties(difficulty) {
  const normalizedDifficulty = Math.max(
    1,
    Math.min(MAX_SESSION_DIFFICULTY, Number.parseInt(difficulty, 10) || 3)
  );

  return Object.fromEntries(
    SESSION_CATEGORY_ORDER.map((category) => [category, normalizedDifficulty])
  );
}

// Hard-code each child's per-category levels here.
const USER_PROFILES = [
  {
    id: "guest",
    name: "Guest",
    defaultDifficulty: 1,
    enableReviewFocus: true,
    avatarStyle: "girlCurls",
    palette: {
      sky: "#f4ecff",
      shirt: "#8f66cf",
      hair: "#a8714d",
      accent: "#f0b6cf",
      eyes: "#6b452e",
    },
  },
  {
    id: "gabriel",
    name: "Gabriel",
    categoryDifficulties: {
      math: 3,
      "addition-subtraction": 3,
      "multiplication-division": 3,
      "place-value-decimals": 3,
      geometry: 3,
      "patterns-sequences": 3,
      "coordinates-functions": 3,
      hebrew: 2,
      science: 3,
      "science-evidence": 3,
      time: 3,
      statistics: 3,
      "negative-numbers": 3,
      percentages: 3,
      algebra: 3,
      "applied-word-problems": 3,
      "visual-math": 3,
      "visual-measurement": 3,
      logic: 3,
      rationality: 3,
      "general-knowledge": 3,
      geography: 3,
      "geography-map": 3,
      history: 3,
      population: 3,
      computing: 3,
      "financial-literacy": 3,
      measurement: 3,
      "charts-and-graphs": 3,
      calendar: 3,
      estimation: 3,
      probability: 3,
      "reading-comprehension": 3,
      "vocabulary-grammar": 3,
      "maps-and-directions": 3,
      "health-and-first-aid": 3,
      nutrition: 3,
      "household-problem-solving": 3,
      fractions: 3,
      "fractions-and-ratios": 3,
      "spatial-reasoning": 3,
    },
    enableReviewFocus: true,
    avatarStyle: "lightCurls",
    palette: {
      sky: "#ecf7ea",
      shirt: "#5ea96f",
      hair: "#9b7653",
      accent: "#ff9a84",
      eyes: "#3a4f63",
    },
  },
  {
    id: "gideon",
    name: "Gideon",
    categoryDifficulties: {
      math: 7,
      "addition-subtraction": 7,
      "multiplication-division": 7,
      "place-value-decimals": 7,
      geometry: 7,
      "patterns-sequences": 7,
      "coordinates-functions": 7,
      hebrew: 7,
      science: 7,
      "science-evidence": 7,
      time: 7,
      statistics: 7,
      "negative-numbers": 7,
      percentages: 7,
      algebra: 7,
      "applied-word-problems": 7,
      "visual-math": 7,
      "visual-measurement": 7,
      logic: 7,
      rationality: 7,
      "general-knowledge": 7,
      geography: 7,
      "geography-map": 7,
      history: 7,
      population: 7,
      computing: 7,
      "financial-literacy": 7,
      measurement: 7,
      "charts-and-graphs": 7,
      calendar: 7,
      estimation: 7,
      probability: 7,
      "reading-comprehension": 7,
      "vocabulary-grammar": 7,
      "maps-and-directions": 7,
      "health-and-first-aid": 7,
      nutrition: 7,
      "household-problem-solving": 7,
      fractions: 7,
      "fractions-and-ratios": 7,
      "spatial-reasoning": 7,
    },
    enableReviewFocus: true,
    avatarStyle: "curlyHair",
    palette: {
      sky: "#e6f6ff",
      shirt: "#4f92d8",
      hair: "#3f2f2a",
      accent: "#f4c869",
      eyes: "#243649",
    },
  },
  {
    id: "noga",
    name: "Noga",
    categoryDifficulties: {
      math: 3,
      "addition-subtraction": 3,
      "multiplication-division": 3,
      "place-value-decimals": 3,
      geometry: 3,
      "patterns-sequences": 3,
      "coordinates-functions": 3,
      hebrew: 3,
      science: 3,
      "science-evidence": 3,
      time: 3,
      statistics: 3,
      "negative-numbers": 3,
      percentages: 3,
      algebra: 3,
      "applied-word-problems": 3,
      "visual-math": 3,
      "visual-measurement": 3,
      logic: 3,
      rationality: 3,
      "general-knowledge": 3,
      geography: 3,
      "geography-map": 3,
      history: 3,
      population: 3,
      computing: 3,
      "financial-literacy": 3,
      measurement: 3,
      "charts-and-graphs": 3,
      calendar: 3,
      estimation: 3,
      probability: 3,
      "reading-comprehension": 3,
      "vocabulary-grammar": 3,
      "maps-and-directions": 3,
      "health-and-first-aid": 3,
      nutrition: 3,
      "household-problem-solving": 3,
      fractions: 3,
      "fractions-and-ratios": 3,
      "spatial-reasoning": 3,
    },
    enableReviewFocus: true,
    avatarStyle: "longHair",
    palette: {
      sky: "#fff1d2",
      shirt: "#e28a63",
      hair: "#e1be5a",
      accent: "#8fb8ff",
      eyes: "#3e8a57",
    },
  },
  {
    id: ADULT_USER_ID,
    name: "Miranda",
    defaultDifficulty: FIXED_ADULT_SESSION_DIFFICULTY,
    categoryDifficulties: createUniformCategoryDifficulties(FIXED_ADULT_SESSION_DIFFICULTY),
    enableReviewFocus: false,
    enableHebrewWritingTail: false,
    avatarStyle: "adultBun",
    palette: {
      sky: "#f6ede8",
      shirt: "#8c6f63",
      hair: "#3b2a26",
      accent: "#d7b19d",
      eyes: "#2c3b49",
    },
  },
];
const CATEGORY_LABELS = {
  math: "Math",
  "addition-subtraction": "Addition & Subtraction",
  "multiplication-division": "Multiplication & Division",
  "place-value-decimals": "Place Value & Decimals",
  geometry: "Geometry & Shapes",
  "patterns-sequences": "Patterns & Sequences",
  "coordinates-functions": "Coordinates & Functions",
  hebrew: "Hebrew",
  "hebrew-writing": "Hebrew Writing",
  science: "Science",
  "science-evidence": "Science Evidence",
  time: "Time",
  statistics: "Statistics",
  "negative-numbers": "Negative Numbers",
  percentages: "Percentages",
  algebra: "Algebra",
  "applied-word-problems": "Applied Word Problems",
  "visual-math": "Visual Math",
  "visual-measurement": "Visual Measurement",
  logic: "Logic",
  rationality: "Rationality",
  "general-knowledge": "General Knowledge",
  geography: "Geography",
  "geography-map": "Geography Map",
  history: "History & Historical Thinking",
  population: "Population",
  computing: "Computing",
  "financial-literacy": "Financial Literacy",
  measurement: "Measurement",
  "charts-and-graphs": "Charts and Graphs",
  calendar: "Calendar",
  estimation: "Estimation",
  probability: "Probability",
  "reading-comprehension": "Reading Comprehension",
  "vocabulary-grammar": "Vocabulary / Grammar",
  "maps-and-directions": "Maps and Directions",
  "health-and-first-aid": "Health and First Aid",
  nutrition: "Nutrition",
  "household-problem-solving": "Household Problem Solving",
  fractions: "Fractions",
  "fractions-and-ratios": "Fractions and Ratios",
  "spatial-reasoning": "Spatial Reasoning",
};
const USER_PROFILE_MAP = Object.fromEntries(USER_PROFILES.map((profile) => [profile.id, profile]));
const DIFFICULTY_LEVEL_STYLES = {
  1: { accent: "#89d48c", text: "#17324a" },
  2: { accent: "#b5de7a", text: "#17324a" },
  3: { accent: "#f3d46b", text: "#17324a" },
  4: { accent: "#f0ab63", text: "#17324a" },
  5: { accent: "#e57a7a", text: "#ffffff" },
  6: { accent: "#d96d8c", text: "#ffffff" },
  7: { accent: "#ca67a4", text: "#ffffff" },
  8: { accent: "#af63bc", text: "#ffffff" },
  9: { accent: "#8b5fd0", text: "#ffffff" },
  10: { accent: "#695ad9", text: "#ffffff" },
};
const NON_HEBREW_DIFFICULTY_WEIGHTS = {
  1: { 1: 1 },
  2: { 2: 0.75, 1: 0.25 },
  3: { 3: 0.7, 2: 0.2, 1: 0.1 },

  // From level 4 up:
  // 70% current level, 20% one level below, 10% two levels below
  4: { 4: 0.7, 3: 0.2, 2: 0.1 },
  5: { 5: 0.7, 4: 0.2, 3: 0.1 },
  6: { 6: 0.7, 5: 0.2, 4: 0.1 },
  7: { 7: 0.7, 6: 0.2, 5: 0.1 },
  8: { 8: 0.7, 7: 0.2, 6: 0.1 },
  9: { 9: 0.7, 8: 0.2, 7: 0.1 },
  10: { 10: 0.7, 9: 0.2, 8: 0.1 },
};
const HEBREW_DIFFICULTY_WEIGHTS = {
  1: { 1: 1 },
  2: { 2: 0.4, 1: 0.6 },
  3: { 3: 0.2, 2: 0.45, 1: 0.35 },
  4: { 4: 0.3, 3: 0.45, 2: 0.25 },
  5: { 5: 0.3, 4: 0.45, 3: 0.25 },
  6: { 6: 0.35, 5: 0.45, 4: 0.2 },
  7: { 7: 0.4, 6: 0.4, 5: 0.2 },
  8: { 8: 0.45, 7: 0.4, 6: 0.15 },
  9: { 9: 0.5, 8: 0.35, 7: 0.15 },
  10: { 10: 0.6, 9: 0.3, 8: 0.1 },
};
const EXTENDED_MATH_CATEGORIES = new Set([
  "math",
  "addition-subtraction",
  "multiplication-division",
  "place-value-decimals",
  "geometry",
  "patterns-sequences",
  "coordinates-functions",
  "statistics",
  "negative-numbers",
  "percentages",
  "time",
  "algebra",
  "applied-word-problems",
  "visual-math",
  "visual-measurement",
  "logic",
  "measurement",
  "charts-and-graphs",
  "calendar",
  "estimation",
  "probability",
  "fractions",
  "fractions-and-ratios",
  "spatial-reasoning",
]);
const SESSION_PRESETS = {
  adaptive: "adaptive",
  "math-heavy": "math-heavy",
  hebrew: "hebrew",
  practice: "practice",
};

// Level numbers are grade numbers. This scope is intentionally short enough to
// show beside the slider while also serving as the app's curriculum contract.
const GRADE_LEVEL_SCOPE = {
  1: "Numbers to 120 · add/subtract within 20 · shapes, length and time",
  2: "Place value to 1,000 · add/subtract within 100 · equal groups",
  3: "Multiplication/division · fractions · area and data",
  4: "Multi-digit operations · fraction equivalence · angles",
  5: "Decimals · fraction operations · volume · coordinate plane",
  6: "Ratios and percent · rational numbers · expressions · statistics",
  7: "Proportions · signed operations · equations · probability",
  8: "Linear functions · exponents · transformations · bivariate data",
  9: "Algebra I · quadratics · coordinate geometry · modeling",
  10: "Geometry/Algebra II · sequences · nonlinear functions · statistics",
};

const PRACTICE_TOPIC_GROUPS = [
  {
    label: "Number & Math Skills",
    icon: "✦",
    categories: [
      "math",
      "addition-subtraction",
      "multiplication-division",
      "place-value-decimals",
      "negative-numbers",
      "percentages",
      "fractions",
      "fractions-and-ratios",
      "algebra",
      "patterns-sequences",
      "coordinates-functions",
      "applied-word-problems",
      "visual-math",
      "estimation",
    ],
  },
  {
    label: "Measure, Data & Space",
    icon: "▦",
    categories: [
      "geometry",
      "measurement",
      "visual-measurement",
      "time",
      "calendar",
      "statistics",
      "charts-and-graphs",
      "probability",
      "spatial-reasoning",
      "logic",
    ],
  },
  {
    label: "Language & Ideas",
    icon: "Aa",
    categories: [
      "hebrew",
      "reading-comprehension",
      "vocabulary-grammar",
      "rationality",
    ],
  },
  {
    label: "Science & Our World",
    icon: "◉",
    categories: [
      "science",
      "science-evidence",
      "geography",
      "geography-map",
      "maps-and-directions",
      "population",
      "history",
      "general-knowledge",
    ],
  },
  {
    label: "Life & Technology",
    icon: "⌂",
    categories: [
      "computing",
      "financial-literacy",
      "health-and-first-aid",
      "nutrition",
      "household-problem-solving",
    ],
  },
];


  window.HomeworkApp.config = {
    OPTION_LABELS,
    SESSION_HISTORY_STORAGE_KEY,
    SELECTED_USER_STORAGE_KEY,
    GOOGLE_SHEETS_REPORT_WEB_APP_URL,
    GOOGLE_SHEETS_REPORT_QUEUE_STORAGE_KEY,
    GOOGLE_SHEETS_REPORT_SOURCE,
    GOOGLE_SHEETS_REPORT_SCHEMA_VERSION,
    MAX_SAVED_SESSIONS,
    QUESTION_COUNT_OPTIONS,
    SPEED_ROUND_QUESTION_COUNT,
    SPEED_ROUND_SECONDS,
    SPEED_ROUND_MS,
    ADULT_USER_ID,
    ADULT_SESSION_DEFAULT_QUESTION_COUNT,
    ADULT_MATH_INTERVAL,
    ADULT_GEOGRAPHY_SHARE,
    MAX_SESSION_DIFFICULTY,
    FIXED_ADULT_SESSION_DIFFICULTY,
    DEFAULT_HEBREW_WRITING_TAIL_COUNT,
    HEBREW_ONLY_WRITING_TAIL_COUNT,
    RESERVED_MAP_CATEGORY,
    LANGUAGE_DRAG_INTERVAL,
    HEBREW_FINAL_LETTER_INTERVAL,
    HEBREW_IMAGE_DRAG_SHARE,
    HEBREW_MATCHING_PAIR_COUNT,
    HEBREW_OPPOSITES_PAIR_COUNT,
    GENERATED_CATEGORY_DRAG_SHARES,
    HEBREW_OPPOSITE_PAIR_DEFINITIONS,
    REVIEW_FOCUS_SHARE,
    REVIEW_RECENCY_DECAY,
    SNAPSHOT_DATE_PATTERN,
    CORE_SESSION_CATEGORIES,
    NON_CORE_SESSION_CATEGORIES,
    REVIEW_FOCUS_ALLOWED_CATEGORIES,
    SESSION_CATEGORY_ORDER,
    CORE_CATEGORY_SHARE,
    createUniformCategoryDifficulties,
    USER_PROFILES,
    CATEGORY_LABELS,
    USER_PROFILE_MAP,
    DIFFICULTY_LEVEL_STYLES,
    NON_HEBREW_DIFFICULTY_WEIGHTS,
    HEBREW_DIFFICULTY_WEIGHTS,
    EXTENDED_MATH_CATEGORIES,
    SESSION_PRESETS,
    GRADE_LEVEL_SCOPE,
    PRACTICE_TOPIC_GROUPS,
  };
})();
