(() => {
  function getElements(rootDocument = document) {
    const document = rootDocument;
    return {
  startScreen: document.getElementById("start-screen"),
  quizScreen: document.getElementById("quiz-screen"),
  resultsScreen: document.getElementById("results-screen"),
  historyScreen: document.getElementById("history-screen"),
  dashboardScreen: document.getElementById("dashboard-screen"),
  startForm: document.getElementById("start-form"),
  userSelector: document.getElementById("user-selector"),
  startFeedback: document.getElementById("start-feedback"),
  historyButton: document.getElementById("history-button"),
  historyBackButton: document.getElementById("history-back-button"),
  historyList: document.getElementById("history-list"),
  historyEmpty: document.getElementById("history-empty"),
  dashboardButton: document.getElementById("dashboard-button"),
  dashboardBackButton: document.getElementById("dashboard-back-button"),
  dashboardExportCsvButton: document.getElementById("dashboard-export-csv-button"),
  dashboardShareCsvButton: document.getElementById("dashboard-share-csv-button"),
  dashboardUserSelector: document.getElementById("dashboard-user-selector"),
  dashboardContent: document.getElementById("dashboard-content"),
  sessionModeLabel: document.getElementById("session-mode-label"),
  questionCount: document.getElementById("question-count"),
  questionCountButtons: Array.from(document.querySelectorAll(".question-count-button")),
  hebrewOnly: document.getElementById("hebrew-only"),
  hebrewOnlyButton: document.getElementById("hebrew-only-button"),
  specialtyWordsOnly: document.getElementById("specialty-words-only"),
  specialtyWordsButton: document.getElementById("specialty-words-button"),
  difficultyMin: document.getElementById("difficulty-min"),
  sessionBuilder: document.getElementById("session-builder"),
  sessionPresetButtons: Array.from(document.querySelectorAll(".builder-preset-button")),
  adaptiveReviewButton: document.getElementById("adaptive-review-button"),
  categoryResetButton: document.getElementById("category-reset-button"),
  categoryBuilderGrid: document.getElementById("category-builder-grid"),
  difficultyLabel: document.getElementById("difficulty-label"),
  difficultySelector: document.getElementById("difficulty-selector"),
  difficultyLevel: document.getElementById("difficulty-level"),
  difficultyValue: document.getElementById("difficulty-value"),
  progressTracker: document.getElementById("progress-tracker"),
  scoreText: document.getElementById("score-text"),
  speedTimer: document.getElementById("speed-timer"),
  speedTimerText: document.getElementById("speed-timer-text"),
  speedTimerFill: document.getElementById("speed-timer-fill"),
  feedback: document.getElementById("feedback"),
  questionNumber: document.getElementById("question-number"),
  questionPrompt: document.getElementById("question-prompt"),
  questionMain: document.getElementById("question-main"),
  questionVisual: document.getElementById("question-visual"),
  questionExtra: document.getElementById("question-extra"),
  answerForm: document.getElementById("answer-form"),
  inputArea: document.getElementById("input-area"),
  answerInput: document.getElementById("answer-input"),
  answerSignButton: document.getElementById("answer-sign-button"),
  answerSubmitButton: document.getElementById("answer-submit-button"),
  choicesArea: document.getElementById("choices-area"),
  dragArea: document.getElementById("drag-area"),
  quizBackButton: document.getElementById("quiz-back-button"),
  quizForwardButton: document.getElementById("quiz-forward-button"),
  resultsTitle: document.getElementById("results-title"),
  resultsSummary: document.getElementById("results-summary"),
  resultsCategorySummary: document.getElementById("results-category-summary"),
  resultsReviewList: document.getElementById("results-review-list"),
  resultsBackButton: document.getElementById("results-back-button"),
  resultsForwardButton: document.getElementById("results-forward-button"),
  restartButton: document.getElementById("restart-button"),
  appUpdateBanner: document.getElementById("app-update-banner"),
  appUpdateButton: document.getElementById("app-update-button"),
};
  }

  window.HomeworkApp.dom = {
    getElements,
  };
})();
